### ISSUE TITLE
Game Crashes with the use of data pack

### ISSUE THREAD

**Issue by BearStew** [apace100/origins-fabric#120]
I have been working on a data pack for this mod and I have looked at tutorials and It keeps crashing. I was wondering if anyone could help me figure it out
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2/20/21 11:17 AM
Description: Loading entity NBT

java.lang.NullPointerException: Loading entity NBT
	at io.github.apace100.origins.origin.OriginLayer.lambda$null$3(OriginLayer.java:78)
	at io.github.apace100.origins.origin.OriginLayer$$Lambda$5357/543561496.test(Unknown Source)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at io.github.apace100.origins.origin.OriginLayer.lambda$contains$4(OriginLayer.java:78)
	at io.github.apace100.origins.origin.OriginLayer$$Lambda$5356/133174057.test(Unknown Source)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at io.github.apace100.origins.origin.OriginLayer.contains(OriginLayer.java:78)
	at io.github.apace100.origins.component.PlayerOriginComponent.fromTag(PlayerOriginComponent.java:199)
	at io.github.apace100.origins.component.PlayerOriginComponent.readFromNbt(PlayerOriginComponent.java:152)
	at dev.onyxstudios.cca.api.v3.component.ComponentV3.fromTag(ComponentV3.java:74)
	at nerdhub.cardinal.components.api.util.container.AbstractComponentContainer.fromTag(AbstractComponentContainer.java:180)
	at net.minecraft.class_1297.handler$zli000$fromTag(class_1297.java:5695)
	at net.minecraft.class_1297.method_5651(class_1297.java:1654)
	at net.minecraft.class_3324.method_14600(class_3324.java:341)
	at net.minecraft.class_3324.method_14570(class_3324.java:138)
	at net.minecraft.class_3248.method_14384(class_3248.java:113)
	at net.minecraft.class_3248.redirect$zgo000$handlePlayerJoin(class_3248.java:562)
	at net.minecraft.class_3248.method_18785(class_3248.java:65)
	at net.minecraft.class_2535.method_10754(class_2535.java:228)
	at net.minecraft.class_3242.method_14357(class_3242.java:173)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$4778/485217789.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at io.github.apace100.origins.origin.OriginLayer.lambda$null$3(OriginLayer.java:78)
	at io.github.apace100.origins.origin.OriginLayer$$Lambda$5357/543561496.test(Unknown Source)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at io.github.apace100.origins.origin.OriginLayer.lambda$contains$4(OriginLayer.java:78)
	at io.github.apace100.origins.origin.OriginLayer$$Lambda$5356/133174057.test(Unknown Source)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1351)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at io.github.apace100.origins.origin.OriginLayer.contains(OriginLayer.java:78)
	at io.github.apace100.origins.component.PlayerOriginComponent.fromTag(PlayerOriginComponent.java:199)
	at io.github.apace100.origins.component.PlayerOriginComponent.readFromNbt(PlayerOriginComponent.java:152)
	at dev.onyxstudios.cca.api.v3.component.ComponentV3.fromTag(ComponentV3.java:74)
	at nerdhub.cardinal.components.api.util.container.AbstractComponentContainer.fromTag(AbstractComponentContainer.java:180)
	at net.minecraft.class_1297.handler$zli000$fromTag(class_1297.java:5695)

-- Entity being loaded --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 190
	Entity Name: josephbres
	Entity's Exact location: -73.61, 67.75, -7.27
	Entity's Block location: World: (-74,67,-8), Chunk: (at 6,4,8 in -5,-1; contains blocks -80,0,-16 to -65,255,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_1297.method_5651(class_1297.java:1654)
	at net.minecraft.class_3324.method_14600(class_3324.java:341)
	at net.minecraft.class_3324.method_14570(class_3324.java:138)
	at net.minecraft.class_3248.method_14384(class_3248.java:113)
	at net.minecraft.class_3248.redirect$zgo000$handlePlayerJoin(class_3248.java:562)
	at net.minecraft.class_3248.method_18785(class_3248.java:65)
	at net.minecraft.class_2535.method_10754(class_2535.java:228)
	at net.minecraft.class_3242.method_14357(class_3242.java:173)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.class_1132.method_3748(class_1132.java:91)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at net.minecraft.server.MinecraftServer$$Lambda$4778/485217789.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1469534536 bytes (1401 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		autoconfig1u: Auto Config v1 Updated 3.2.2
		cardinal-components: Cardinal Components API 2.7.12
		cardinal-components-base: Cardinal Components API (base) 2.7.12
		cardinal-components-block: Cardinal Components API (blocks) 2.7.12
		cardinal-components-chunk: Cardinal Components API (chunks) 2.7.12
		cardinal-components-entity: Cardinal Components API (entities) 2.7.12
		cardinal-components-item: Cardinal Components API (items) 2.7.12
		cardinal-components-level: Cardinal Components API (world saves) 2.7.12
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 2.7.12
		cardinal-components-util: Cardinal Components API (utilities) 2.7.12
		cardinal-components-world: Cardinal Components API (worlds) 2.7.12
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.8.1
		fabric: Fabric API 0.30.3+1.16
		fabric-api-base: Fabric API Base 0.2.1+9354966b7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.0.10+ca58154a7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.11+9354966b7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.6+9354966b7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.4+9354966b7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.4+9354966b7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.5+9354966b7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.11.1
		fallflyinglib: FallFlyingLib 1.1.0
		java: Java HotSpot(TM) 64-Bit Server VM 8
		minecraft: Minecraft 1.16.5
		origins: Origins 0.4.7
		reach-entity-attributes: Reach Entity Attribute 1.0.1
	Player Count: 0 / 8; []
	Data Packs: vanilla (incompatible), Fabric Mods, file/Soupbois
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by BearStew** [comment]
fixed
