### ISSUE TITLE
New Merling not backwards compatible

### ISSUE THREAD

**Issue by Lanternglow** [apace100/origins-fabric#17]
Trying to load a world playing a Merling origin not working with Origins 1.16-0.2.6

[22:17:51] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Loading entity NBT
	at net.minecraft.class_3242.method_14357(class_3242.java:173) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:884) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:813) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:93) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:672) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_262]
Caused by: java.lang.ClassCastException: net.minecraft.class_2487 cannot be cast to net.minecraft.class_2481
	at io.github.apace100.origins.power.ToggleNightVisionPower.fromTag(ToggleNightVisionPower.java:33) ~[Origins-1.16-0.2.6.jar:?]
	at io.github.apace100.origins.component.PlayerOriginComponent.fromTag(PlayerOriginComponent.java:141) ~[Origins-1.16-0.2.6.jar:?]
	at io.github.apace100.origins.component.PlayerOriginComponent.fromTag(PlayerOriginComponent.java:112) ~[Origins-1.16-0.2.6.jar:?]
	at nerdhub.cardinal.components.api.util.container.AbstractComponentContainer.fromTag(AbstractComponentContainer.java:106) ~[b18299b9-8fbc-4b73-8ea2-34688a6db860.jar:?]
	at net.minecraft.class_1297.handler$bcl000$fromTag(class_1297.java:6642) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_1297.method_5651(class_1297.java:1636) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3324.method_14600(class_3324.java:338) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:135) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3248.method_14384(class_3248.java:111) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3248.method_18785(class_3248.java:63) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:229) ~[intermediary-minecraft-1.16.1-client.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:170) ~[intermediary-minecraft-1.16.1-client.jar:?]
	... 6 more

**Comment by Lanternglow** [comment]
Creating a new world and selecting Merling origin works fine.

**Comment by apace100** [comment]
Thanks for the report, fixed in the newest version!
