### ISSUE TITLE
origins crashed while starting up server 

### ISSUE THREAD

**Issue by Swiftform** [apace100/origins-fabric#190]
[18:29:12] [main/INFO]: Loading for game Minecraft 1.16.5
[18:29:12] [ForkJoinPool-1-worker-1/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
- Unsupported root entry "$schema" at line 2 column 14
[18:29:12] [ForkJoinPool-1-worker-2/WARN]: The mod "cardinal-components-base" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[18:29:12] [ForkJoinPool-1-worker-2/WARN]: The mod "cardinal-components-entity" contains invalid entries in its mod json:
- Unsupported root entry "side" at line 8 column 11
[18:29:12] [ForkJoinPool-1-worker-3/WARN]: Non-Fabric mod JAR at "C:\Users\camos\Desktop\1.16.5 modded\mods\upgrade_aquatic-1.16.5-3.0.1.jar", ignoring
[18:29:13] [main/WARN]: Warnings were found! 
 - Mod 'Villager Fix' (villagerfix) recommends version 1.14.6 or later of mod modmenu, which is missing!
	 - You must install version 1.14.6 or later of modmenu.
 - Mod 'Colormatic' (colormatic) recommends version 1.12.0 or later of mod modmenu, which is missing!
	 - You must install version 1.12.0 or later of modmenu.
[18:29:13] [main/INFO]: [FabricLoader] Loading 122 mods: fallflyinglib@1.1.0, fabric-keybindings-v0@0.2.1+ca58154a7d, roughlyenoughitems-api@5.10.184, fabricloader@0.11.2, org_jetbrains_kotlinx_kotlinx-serialization-json-jvm@1.1.0, hydrogen@0.2, fabric-dimensions-v1@2.0.6+9354966b7d, immersive-cursedness@1.2.1, java@8, timecraft@0.4.3, fabric-game-rule-api-v1@1.0.6+ca58154a7d, adventurez@1.1.7, fabric-api-base@0.2.1+9354966b7d, villagernames@1.6.0, fiber@0.23.0-2, alloys@1.1.0, villagerfix@1.4.1+1.16.2, randompatches@2.4.5-fabric, org_jetbrains_kotlin_kotlin-stdlib@1.4.31, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, terraform-wood-api-v1@1.0.2, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.4.31, fabric@0.32.0+1.16, fabric-networking-v0@0.3.2+ca58154a7d, dawn@1.7, fabric-api-lookup-api-v1@1.0.0+dc716ea17d, fabric-screen-handler-api-v1@1.1.5+9354966b7d, repurposed_structures@1.16.5-1.8.7, wild_explorer@1.3.2, phosphor@0.7.1+build.11, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.4.31, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, roughlyenoughitems-runtime@5.10.184, angerable-patch@1.1.0-1.16.4, terraform-tree-api-v1@1.0.5, cloth-client-events-v0@1.5.47, voyager@1.0.0, fabric-crash-report-info-v1@0.1.3+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-language-kotlin@1.5.0+kotlin.1.4.31, overworld_two@1.0.4, origins@0.6.1, fabric-key-binding-api-v1@1.0.4+9354966b7d, nourish@1.2.1, fabric-language-scala@1.0.0, cloth-config2@4.11.14, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.4.2, fabric-resource-loader-v0@0.4.2+ca58154a7d, chunkpregen@0.3.3, net_gegy1000_just-now@0.1.0-SNAPSHOT, org_jetbrains_kotlin_kotlin-reflect@1.4.31, cardinal-components-entity@2.7.1, architectury@1.8.131, colormatic@2.2.8+mc.1.16.3, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-commands-v0@0.2.2+ca58154a7d, cardinal-components-base@2.7.1, fabric-mining-levels-v0@0.1.3+ca58154a7d, fallingtree@2.10.2, fabric-networking-api-v1@1.0.1+ca58154a7d, krypton@0.1.2, earthtojavamobs@1.6.1+1.16.4, fabric-models-v0@0.2.1+ca58154a7d, fabric-item-groups-v0@0.2.3+ca58154a7d, tic_tacs@0.1.2, terraform-shapes-api-v1@1.0.4, fabric-renderer-api-v1@0.4.1+ca58154a7d, craftpresence@1.7.6, savemystronghold@1.16.4-1.0, fabric-structure-api-v1@1.1.4+ca58154a7d, allure@1.2.8, lithium@0.6.4, fabric-containers-v0@0.1.11+9354966b7d, fabric-object-builder-api-v1@1.9.4+9354966b7d, terraform-config-api-v1@1.0.2, org_jetbrains_kotlinx_kotlinx-serialization-core-jvm@1.1.0, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, terraform-surfaces-api-v1@1.0.2, campanion@1.3.5, fabric-textures-v0@1.0.6+ca58154a7d, com_electronwill_night-config_core@3.6.3, lazydfu@0.1.2, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, starlight@0.0.2, reach-entity-attributes@1.0.1, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, traverse@3.3.2, fabric-renderer-registries-v1@2.2.1+ca58154a7d, fabric-loot-tables-v1@1.0.2+ca58154a7d, fabric-particles-v1@0.2.4+ca58154a7d, autoconfigtoml@1.0.0-fabric, nofade@1.16.5-1.0.1, terraform-biome-builder-api-v1@1.0.3, roughlyenoughitems-default-plugin@5.10.184, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, bedrockwaters@1.4.3+1.16.4, minecraft@1.16.5, physicsmod@1.0.0, fabric-command-api-v1@1.1.0+f9b3753b7d, jankson@3.0.1+j1.2.0, cloth-basic-math@0.5.1, fabric-screen-api-v1@1.0.0+c045166c7d, fabric-renderer-indigo@0.4.4+ca58154a7d, org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm@1.4.2, com_electronwill_night-config_toml@3.6.3, roughlyenoughitems@5.10.184, fabric-item-api-v1@1.2.1+ca58154a7d, libgui@3.0.0-beta.1+1.16.2-rc2, fabric-entity-events-v1@1.0.3+ca58154a7d, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-rendering-v1@1.5.1+ca58154a7d, terraform-overworld-biome-extensions-api-v1@1.0.2, autoconfig1u@3.3.1, fabric-content-registries-v0@0.2.1+ca58154a7d, fabric-tag-extensions-v0@1.1.1+ca58154a7d, fastfurnace@2.3, fabric-biome-api-v1@3.1.1+ca58154a7d, appleskin@1.0.11, zoob@3.0.0, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, libstructure@1.5, fabric-object-builders-v0@0.7.2+ca58154a7d
[18:29:13] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/camos/Desktop/1.16.5%20modded/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[18:29:17] [main/WARN]: Error loading class: net/minecraft/class_761 (java.lang.ClassNotFoundException: ne[18:29:17] [main/WARN]: Force-disabling mixin 'alloc.chunk_ticking.ChunkTicketManagerMixin' as rule 'mixin.alloc.chunk_ticking' (added by mods [tic_tacs]) disables it and children
[18:29:17] [main/WARN]: Force-disabling mixin 'alloc.chunk_ticking.ServerChunkManagerMixin' as rule 'mixin.alloc.chunk_ticking' (added by mods [tic_tacs]) disables it and children
[18:29:17] [main/WARN]: Force-dis[18:29:17] [main/WARN]: Error loading class: net/minecraft/class_746 (java.lang.ClassNotFoundException: net/minecraft/class_746)
[18:29:17] [main/WARN]: @Mixin target net.minecraft.class_746 was not found architectury.mixins.json:PlayerAttackInvoker
[18:29:17] [main/WARN]: Error loading class: net/minecraft/class_745 (java.lang.ClassNotFoundException: net/minecraft/class_745)
[18:29:17] [main/WARN]: @Mixin target net.minecraft.class_745 was not found architectury.mixins.json:PlayerAttackInvoker
[18:29:17] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-api-v1.mixins.json:accessor.EntityTrackerAccessor and should be specified in value
[18:29:17] [main/WARN]: Error loading class: net/minecraft/class_2535$1 (java.lang.ClassNotFoundException: net/minecraft/class_2535$1)
[18:29:17] [main/WARN]: @Mixin target net/minecraft/class_2535$1 was not found randompatches.mixins.json:timeouts.ChannelInitializerMixin
[18:29:18] [main/FATAL]: Mixin apply failed origins.mixins.json:LivingEntityMixin -> net.minecraft.class_1309: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Variable modifier target for net/minecraft/class_1309::doAvianSlowFalling was removed by another injector [INJECT Applicator Phase -> origins.mixins.json:LivingEntityMixin -> Apply Injections ->  -> Inject -> origins.mixins.json:LivingEntityMixin->@ModifyVariable::doAvianSlowFalling(D)D]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Variable modifier target for net/minecraft/class_1309::doAvianSlowFalling was removed by another injector [INJECT Applicator Phase -> origins.mixins.json:LivingEntityMixin -> Apply Injections ->  -> Inject -> origins.mixins.json:LivingEntityMixin->@ModifyVariable::doAvianSlowFalling(D)D]
	at org.spongepowered.asm.mixin.injection.modify.ModifyVariableInjector.inject(ModifyVariableInjector.java:143) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:264) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:385) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1284) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric-server-launch.jar:?]
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_271]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_271]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_271]
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:163) ~[fabric-server-launch.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_271]
	at net.minecraft.class_2246.<clinit>(class_2246.java:99) ~[intermediary-server.jar:?]
	at net.minecraft.class_3523.<clinit>(class_3523.java:13) ~[intermediary-server.jar:?]
	at net.minecraft.class_5471.<clinit>(class_5471.java:11) ~[intermediary-server.jar:?]
	at net.minecraft.class_5458.method_30573(class_5458.java:44) ~[intermediary-server.jar:?]
	at net.minecraft.class_5458.method_30566(class_5458.java:75) ~[intermediary-server.jar:?]
	at java.util.LinkedHashMap.forEach(Unknown Source) [?:1.8.0_271]
	at net.minecraft.class_5458.<clinit>(class_5458.java:74) [intermediary-server.jar:?]
	at net.minecraft.class_2378.<clinit>(class_2378.java:237) [intermediary-server.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:42) [intermediary-server.jar:?]
	at net.minecraft.server.Main.main(Main.java:87) [intermediary-server.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_271]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_271]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_271]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]

This happened in the first time I tried booting up my server. Origins don't work?

**Comment by Swiftform** [comment]
When I remove origins, it works

**Comment by apace100** [comment]
This seems like an incompatibility with another mod.
Seeing as you have tic-tacs installed and that is known to be incompatible with Origins, it's probably that.

**Comment by Swiftform** [comment]
> This seems like an incompatibility with another mod.
> Seeing as you have tic-tacs installed and that is known to be incompatible with Origins, it's probably that.

ok ill try deleting it.
