### ISSUE TITLE
Can't play as a human?

### ISSUE THREAD

**Issue by IllicitComrade** [apace100/origins-fabric#23]
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 8/17/20 6:05 PM
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraft.class_327.method_30881(Lnet/minecraft/class_4587;Lnet/minecraft/class_2561;FFI)I
	at mcp.mobius.waila.overlay.Tooltip.draw(Tooltip.java:77)
	at mcp.mobius.waila.overlay.OverlayRenderer.renderOverlay(OverlayRenderer.java:84)
	at mcp.mobius.waila.overlay.OverlayRenderer.renderOverlay(OverlayRenderer.java:57)
	at mcp.mobius.waila.overlay.WailaTickHandler.renderOverlay(WailaTickHandler.java:61)
	at net.minecraft.class_757.handler$zfp000$renderOverlay(class_757.java:1391)
	at net.minecraft.class_757.method_3192(class_757.java:584)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:654)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at mcp.mobius.waila.overlay.Tooltip.draw(Tooltip.java:77)
	at mcp.mobius.waila.overlay.OverlayRenderer.renderOverlay(OverlayRenderer.java:84)
	at mcp.mobius.waila.overlay.OverlayRenderer.renderOverlay(OverlayRenderer.java:57)
	at mcp.mobius.waila.overlay.WailaTickHandler.renderOverlay(WailaTickHandler.java:61)
	at net.minecraft.class_757.handler$zfp000$renderOverlay(class_757.java:1391)

-- Affected level --
Details:
	All players: 1 total; [class_746['CraftingwithJ'/212, l='ClientLevel', x=69.50, y=72.00, z=104.50]]
	Chunk stats: Client Chunk Cache: 1369, 841
	Level dimension: minecraft:overworld
	Level spawn location: World: (64,70,96), Chunk: (at 0,4,0 in 4,6; contains blocks 64,0,96 to 79,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 155 game time, 155 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2181)
	at net.minecraft.class_310.method_1514(class_310.java:677)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1042197344 bytes (993 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		betternether: Better Nether 3.5.4
		blackstonetools: Blackstone Tools 1.2.0+1.16.1
		cardinal-components-base: Cardinal Components API (base) 2.4.0
		cardinal-components-entity: Cardinal Components API (entities) 2.4.0
		cinderscapes: Cinderscapes 1.0.7+build.43-1.16.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.5.6
		dynamicsoundfilters: Dynamic Sound Filters 1.1.2+1.16.1
		fabric: Fabric API 0.17.0+build.386-1.16.1
		fabric-api-base: Fabric API Base 0.1.3+12a8474c02
		fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
		fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030f02
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.0+fe81e12502
		fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c502
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+e83e061c02
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
		fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.7+2242e77202
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
		fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+34d6c87102
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+be551d3c02
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
		fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.1+91fca5cd02
		fabricloader: Fabric Loader 0.9.1+build.205
		jankson: Jankson 3.0.0+j1.2.0
		libcd: LibCapableData 2.5.0+1.16.1
		minecraft: Minecraft 1.16.1
		modmenu: Mod Menu 1.14.5+build.30
		origins: Origins 1.16-0.3.4
		parchment: Parchment 1.0.2+1.15.2
		pumice: Pumice 0.0.1
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		shapes: Shapes 2.0.0+build.10
		terraform: Terraform 2.1.7+build.31
		torridvision: Torrid Vision 0.0.1
		waila: Hwyla 1.9.22
	Launched Version: fabric-loader-0.9.1+build.205-1.16.1
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) UHD Graphics GL version 4.6.0 - Build 26.20.100.7642, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	CPU: 8x Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz

**Comment by apace100** [comment]
Hi. From the log it looks like an issue with WAILA/HWYLA and not Origins. Is it really only the Human origin that causes the problem? If so, when did the error occur? Directly when you chose Human, or shortly after?

**Comment by IllicitComrade** [comment]
Hi, after doing some research, turns out it was a hwyla issue, and I
managed to fix the issue on my own. Sorry for bothering you. Enjoy the rest
of your day.
