### ISSUE TITLE
boot loop on server

### ISSUE THREAD

**Issue by lnfranos** [apace100/origins-fabric#253]
18.04 21:42:41 [Multicraft] Starting server!
18.04 21:42:41 [Multicraft] Loaded config for "Fabric 1.16.5 (Lithium + Phosphor)"
18.04 21:42:42 [Multicraft] Updating eula.txt file
18.04 21:42:42 [Server] INFO WARNING: Error loading config file: .dockercfg: $HOME is not defined
18.04 21:42:42 [Server] INFO WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
18.04 21:42:45 [Server] main/INFO Loading for game Minecraft 1.16.5
18.04 21:42:45 [Server] main/FATAL A critical error occurred
18.04 21:42:45 [Server] INFO net.fabricmc.loader.discovery.ModResolutionException: Duplicate versions for mod ID 'lithium': [0.6.0 at /mods/lithium-fabric-mc1.16.4-0.6.0.jar], [0.6.4 at /mods/lithium-fabric-mc1.16.5-0.6.4.jar]
18.04 21:42:45 [Server] INFO at net.fabricmc.loader.discovery.ModCandidateSet.toSortedSet(ModCandidateSet.java:89) ~[Fabric_Latest_1.16.5.jar:?]
18.04 21:42:45 [Server] INFO at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:101) ~[Fabric_Latest_1.16.5.jar:?]
18.04 21:42:45 [Server] INFO at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:787) ~[Fabric_Latest_1.16.5.jar:?]
18.04 21:42:45 [Server] INFO at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:211) ~[Fabric_Latest_1.16.5.jar:?]
18.04 21:42:45 [Server] INFO at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:201) [Fabric_Latest_1.16.5.jar:?]
18.04 21:42:45 [Server] INFO at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:126) [Fabric_Latest_1.16.5.jar:?]
18.04 21:42:45 [Server] INFO at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [Fabric_Latest_1.16.5.jar:?]
18.04 21:42:45 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275]
18.04 21:42:45 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275]
18.04 21:42:45 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
18.04 21:42:45 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
18.04 21:42:45 [Server] INFO at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [Fabric_Latest_1.16.5.jar:?]
18.04 21:42:45 [Server] INFO at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [Fabric_Latest_1.16.5.jar:?]
18.04 21:42:45 [Server] INFO at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [Fabric_Latest_1.16.5.jar:?]

**Comment by clarence112** [comment]
> 18.04 21:42:45 [Server] INFO net.fabricmc.loader.discovery.ModResolutionException: Duplicate versions for mod ID 'lithium': [0.6.0 at /mods/lithium-fabric-mc1.16.4-0.6.0.jar], [0.6.4 at /mods/lithium-fabric-mc1.16.5-0.6.4.jar]

You have two copies of lithium installed
