### ISSUE TITLE
Origins + FabricProxy

### ISSUE THREAD

**Issue by JulianN97** [apace100/origins-fabric#267]
I don't know how to describe that but for some of my friends when they join a fabric server from velocity something goes wrong. We all use the same files and versions.

**FabricProxy.toml**
```
BungeeCord = false
BungeeCordWorkaround = true
Velocity = true
allowBypassProxy = true
```

**Versions that me and my friends use**
Minecraft version: 1.16.5
FabricProxy version: 1.4.7
Fabric API version: 0.33.0+1.16
Velocity version: 1.1.5
Origins version: 0.7.0

**Server log**
```
[20:44:51 INFO]: [server connection] Qe_r -> lobby has disconnected
[20:44:51 ERROR]: [server connection] Qe_r -> smp: exception encountered in com.velocitypowered.proxy.connection.backend.BackendPlaySessionHandler@4c4db52c
io.netty.handler.codec.CorruptedFrameException: Error decoding class com.velocitypowered.proxy.protocol.packet.AvailableCommands Direction CLIENTBOUND Protocol 1.16.4 State PLAY ID 10
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.handleDecodeFailure(MinecraftDecoder.java:128) ~[velocity-1.1.5.jar:1.1.5]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:83) ~[velocity-1.1.5.jar:1.1.5]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.channelRead(MinecraftDecoder.java:58) ~[velocity-1.1.5.jar:1.1.5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-1.1.5.jar:1.1.5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-1.1.5.jar:1.1.5]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-1.1.5.jar:1.1.5]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[velocity-1.1.5.jar:1.1.5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-1.1.5.jar:1.1.5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-1.1.5.jar:1.1.5]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-1.1.5.jar:1.1.5]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[velocity-1.1.5.jar:1.1.5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-1.1.5.jar:1.1.5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-1.1.5.jar:1.1.5]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-1.1.5.jar:1.1.5]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[velocity-1.1.5.jar:1.1.5]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[velocity-1.1.5.jar:1.1.5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-1.1.5.jar:1.1.5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-1.1.5.jar:1.1.5]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[velocity-1.1.5.jar:1.1.5]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[velocity-1.1.5.jar:1.1.5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[velocity-1.1.5.jar:1.1.5]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[velocity-1.1.5.jar:1.1.5]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[velocity-1.1.5.jar:1.1.5]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[velocity-1.1.5.jar:1.1.5]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[velocity-1.1.5.jar:1.1.5]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[velocity-1.1.5.jar:1.1.5]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[velocity-1.1.5.jar:1.1.5]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[velocity-1.1.5.jar:1.1.5]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[velocity-1.1.5.jar:1.1.5]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.IllegalArgumentException: Argument type identifier origins:layer unknown.
	at com.velocitypowered.proxy.protocol.packet.brigadier.ArgumentPropertyRegistry.deserialize(ArgumentPropertyRegistry.java:74) ~[velocity-1.1.5.jar:1.1.5]
	at com.velocitypowered.proxy.protocol.packet.AvailableCommands.deserializeNode(AvailableCommands.java:206) ~[velocity-1.1.5.jar:1.1.5]
	at com.velocitypowered.proxy.protocol.packet.AvailableCommands.decode(AvailableCommands.java:87) ~[velocity-1.1.5.jar:1.1.5]
	at com.velocitypowered.proxy.protocol.netty.MinecraftDecoder.tryDecode(MinecraftDecoder.java:81) ~[velocity-1.1.5.jar:1.1.5]
	... 28 more
[20:44:51 INFO]: [server connection] Qe_r -> smp has disconnected
[20:44:51 INFO]: [server connection] Qe_r -> lobby has connected
```

**Comment by JulianN97** [comment]
Fixed - installed CrossSnitch mod to my origins smp.
