### ISSUE TITLE
[Netty Client IO #5/ERROR]: Encountered exception while handling in channel with name "origins:power_list" java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by BusterZlista2** [apace100/origins-fabric#325]
This error happened to me and it keeps on happening whenever I join my friend's server, when it loads my inventory that is when it crashes.

[02:39:02] [Netty Client IO #5/ERROR]: Encountered exception while handling in channel with name "origins:power_list"
java.lang.NullPointerException: null
	at io.github.apace100.origins.power.factory.condition.ConditionType.read(ConditionType.java:30) ~[Origins-1.16.5-0.7.3.jar:?]
	at io.github.apace100.origins.util.SerializableDataType.receive(SerializableDataType.java:509) ~[Origins-1.16.5-0.7.3.jar:?]
	at io.github.apace100.origins.util.SerializableData.lambda$read$1(SerializableData.java:51) ~[Origins-1.16.5-0.7.3.jar:?]
	at java.util.HashMap.forEach(Unknown Source) ~[?:1.8.0_271]
	at io.github.apace100.origins.util.SerializableData.read(SerializableData.java:46) ~[Origins-1.16.5-0.7.3.jar:?]
	at io.github.apace100.origins.power.factory.PowerFactory.read(PowerFactory.java:70) ~[Origins-1.16.5-0.7.3.jar:?]
	at io.github.apace100.origins.networking.ModPacketsS2C.receivePowerList(ModPacketsS2C.java:134) ~[Origins-1.16.5-0.7.3.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:97) ~[de45e554-70ac-4c51-a400-d688648bed80.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:39) ~[de45e554-70ac-4c51-a400-d688648bed80.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:100) [de45e554-70ac-4c51-a400-d688648bed80.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:89) [de45e554-70ac-4c51-a400-d688648bed80.jar:?]
	at net.minecraft.class_634.handler$zpj000$handleCustomPayload(class_634.java:2474) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_634.method_11152(class_634.java) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_2658.method_11457(class_2658.java:65) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_2658.method_11054(class_2658.java:10) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:156) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:147) [intermediary-minecraft-1.16.5-client.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:52) [intermediary-minecraft-1.16.5-client.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [netty-all-4.1.25.Final.jar:4.1.25.Final]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_271]

**Comment by Lerrissirrel** [comment]
For what it's worth, I've got what looks to my untrained eye, like the same thing.  Some few log lines are different from the OP.  I'm touching Minecraft modding (and minecraft for that matter) for the first time as IT support for my daughter who is desperate to connect to her friend's server.  So I may be missing something that's common knowledge.

The full log is here: [https://gist.github.com/Lerrissirrel/e2880a0cb690e3cdfebe547cff0fdb3f](https://gist.github.com/Lerrissirrel/e2880a0cb690e3cdfebe547cff0fdb3f)

Running 16.5 obviously, with fabric-loader-0.11.3-1.16.5 and mod folder contains only:

fabric-api-0.35.0+1.16.jar
moborigins-1.4.0.jar
Origins-1.16.5-0.7.3.jar
Origins-Classes-1.16.5-1.1.1.jar

Thanks for any help!
