### ISSUE TITLE
This server requires you to install the Apoli mod

### ISSUE THREAD

**Issue by NovuaNET** [apace100/origins-fabric#363]
Dispite having the exact same mod installed - i am running a velocity powered server and with your new update 1.17 including this Apoli mod. i am being told to install it

**Comment by NovuaNET** [comment]
Add+

Single player works just fine

**Comment by Grondini99** [comment]
Thank you so much for bringing this up. I've looked everywhere and I cannot find any way to fix this.

**Comment by Frogperson** [comment]
Same issue. My modpack with just Origins, FabricAPI, and RPGstats installed crashes the server, but loads fine in singleplayer.

Here's the latest.log file:
```
[03:20:16] [main/INFO]: Loading for game Minecraft 1.17
[03:20:16] [main/FATAL]: A critical error occurred
net.fabricmc.loader.discovery.ModResolutionException: Could not find required mod: origins requires {apoli @ [>=1.0.1]}
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:198) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.resolve(ModResolver.java:832) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.FabricLoader.setup(FabricLoader.java:195) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.FabricLoader.load(FabricLoader.java:185) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:132) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:68) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:114) [fabric-server-launch.jar:?]
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:56) [fabric-server-launch.jar:?]
Caused by: net.fabricmc.loader.util.sat4j.specs.ContradictionException: Creating Empty clause ?
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.propagationCheck(Clauses.java:117) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.cnf.Clauses.sanityCheck(Clauses.java:97) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.constraints.MixedDataStructureDanielWL.createClause(MixedDataStructureDanielWL.java:81) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.util.sat4j.minisat.core.Solver.addClause(Solver.java:401) ~[fabric-server-launch.jar:?]
	at net.fabricmc.loader.discovery.ModResolver.findCompatibleSet(ModResolver.java:195) ~[fabric-server-launch.jar:?]
	... 12 more
	```

**Comment by apace100** [comment]
Apoli is a library mod which is included within Origins now. The functionality was part of Origins before, but it has been extracted out of the mod, so other mods can make use of it as well. You don't need to install it separately.

This probably happens because the server you're trying to run it on (or your client, if it's the client), does not have access to Java 16. Since Minecraft 1.17, it relies on Java 16 instead of Java 8. So you might have to install that. (The vanilla Minecraft launcher installs it automatically for use with Minecraft, but other applications won't have access to that installation).

I don't know why this is the error that pops up then, but it's something I intend to figure out. Let me know if installing Java 16 solves your problem.

**Comment by Frogperson** [comment]
Ah that was indeed it! Switching to Java 16 fixed the issue and the server starts up without any errors now. Thanks!
