### ISSUE TITLE
Error before start

### ISSUE THREAD

**Issue by Tanahishi** [apace100/origins-fabric#44]
The game crashed whilst unexpected error
Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
Exit Code: -1

I don't know why it says this. i have all the items needed to run it.

**Comment by apace100** [comment]
I'd need more information to figure out what the problem is. A full log as well as a complete list of mods you used would help me track down the problem! Thanks.

**Comment by Tanahishi** [comment]
here is everything the detailed report tells me. 

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 10/27/20 7:24 PM
Description: Initializing game

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:148)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_898.method_23167(class_898.java:103)
	at net.minecraft.class_898.<init>(class_898.java:216)
	at net.minecraft.class_310.<init>(class_310.java:513)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:227)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector modifyEquippedStackToElytra(Lnet/minecraft/class_1799;Lnet/minecraft/class_4587;Lnet/minecraft/class_4597;ILnet/minecraft/class_1309;FFFFFF)Lnet/minecraft/class_1792; in origins.mixins.json:ElytraFeatureRendererMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap Origins-1.16.3-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
	... 17 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:148)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraft.class_898.method_23167(class_898.java:103)
	at net.minecraft.class_898.<init>(class_898.java:216)
	at net.minecraft.class_310.<init>(class_310.java:513)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:227)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 720206688 bytes (686 MB) / 1308622848 bytes (1248 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		amecsapi: Amecs API 1.1.1+mc1.16-rc1
		autoconfig1u: Auto Config v1 Updated 3.2.2
		autoswitch: AutoSwitch 2.11.3
		autoswitch-api: AutoSwitch API 1.0.0
		backslot: BackSlot 1.1.2
		bedspreads: Bedspreads 1.2.0-1.16.3
		cardinal-components-base: Cardinal Components API (base) 2.7.1
		cardinal-components-entity: Cardinal Components API (entities) 2.7.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.8.1
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		fabric: Fabric API 0.23.0+build.410-1.16
		fabric-api-base: Fabric API Base 0.1.3+12a8474c95
		fabric-biome-api-v1: Fabric Biome API (v1) 2.0.0+c29459ab95
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8995
		fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339895
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083695
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f95
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86695
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d95
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db295
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b95
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.2+f8ac1db295
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db295
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963695
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c695
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c595
		fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b2095
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea18895
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9995
		fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db295
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b95
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f95
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.0+c270b09895
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.0+432ea18895
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e95
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.5.2+3c53fe3395
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.1+f8ac1db295
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.1+f8ac1db295
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db295
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db295
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db295
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db295
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db295
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.1+facf3bbf95
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+8724984195
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db295
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c5995
		fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb895
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.3+f8ac1db295
		fabricloader: Fabric Loader 0.10.1+build.209
		fallflyinglib: FallFlyingLib 1.1.0
		minecraft: Minecraft 1.16.3
		mjmod: Daggers 1.0.0
		mm: Manningham Mills 2.1
		moretotems: More Totems 2.7.0
		optifabric: OptiFabric 1.6.4
		org_aeonbits_owner_owner: owner 1.0.10
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
		origins: Origins 0.4.1
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		torohealth: ToroHealth Damage Indicators 1.16.3-fabric-1
		umollu_ash: ASH - Another Simple HUD 1.1.10
		waila: Hwyla 1.9.22
		xaerominimap: Xaero's Minimap 20.25.0
		xaeroworldmap: Xaero's World Map 1.11.0
	Launched Version: fabric-loader-0.10.1+build.209-1.16.3
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: Intel(R) HD Graphics 4600 GL version 4.3.0 - Build 20.19.15.5126, Intel
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 4x Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz
	OptiFine Version: OptiFine_1.16.3_HD_U_G4_pre1
	OptiFine Build: 20200924-111308
	Render Distance Chunks: 14
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Builders_Modded_Shaders_V2.4.1.zip
	OpenGlVersion: 4.3.0 - Build 20.19.15.5126
	OpenGlRenderer: Intel(R) HD Graphics 4600
	OpenGlVendor: Intel
	CpuCount: 4

**Comment by apace100** [comment]
Ah, yeah. This is caused by an incompatibility with OptiFine. I had another user report this to me and ask for a compatible version. If you join the Origins Discord server, or just message me directly on Discord (Apace#9324), I can send you a compatible version as well. However, I had to remove a feature of my mod to make it compatible: you will not be able to use lava vision powers (which don't exist on any Origins by default, but could be part of some datapack you might wanna use).

Otherwise you could also have a look at this page for some OptiFine alternatives: https://gist.github.com/LambdAurora/1f6a4a99af374ce500f250c6b42e8754
