### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "io.github.apace100.origins.origin.OriginLayer.getIdentifier()" because the return value of "java.util.Map$Entry.getKey()" is null

### ISSUE THREAD

**Issue by NoeMastrorillo** [apace100/origins-fabric#479]
Whenever i try to change origin with the orb of origin on my server i get the following error :
```
Error executing task on Server
java.lang.NullPointerException: Cannot invoke "io.github.apace100.origins.origin.OriginLayer.getIdentifier()" because the return value of "java.util.Map$Entry.getKey()" is null
at io.github.apace100.origins.component.PlayerOriginComponent.writeToNbt(PlayerOriginComponent.java:200) ~[Origins-1.18-1.3.1.jar:?]
at dev.onyxstudios.cca.api.v3.component.sync.AutoSyncedComponent.writeSyncPacket(AutoSyncedComponent.java:84) ~[cardinal-components-base-4.0.0-aha.1+21w37a-216749c0a581a4e8.jar:?]
at net.minecraft.class_1297.toComponentPacket(class_1297.java:5077) ~[server-intermediary.jar:?]
at dev.onyxstudios.cca.api.v3.component.ComponentKey.syncWith(ComponentKey.java:236) ~[cardinal-components-base-4.0.0-aha.1+21w37a-216749c0a581a4e8.jar:?]
at dev.onyxstudios.cca.api.v3.component.ComponentKey.sync(ComponentKey.java:166) ~[cardinal-components-base-4.0.0-aha.1+21w37a-216749c0a581a4e8.jar:?]
at dev.onyxstudios.cca.api.v3.component.ComponentKey.sync(ComponentKey.java:128) ~[cardinal-components-base-4.0.0-aha.1+21w37a-216749c0a581a4e8.jar:?]
at io.github.apace100.origins.component.OriginComponent.sync(OriginComponent.java:41) ~[Origins-1.18-1.3.1.jar:?]
at io.github.apace100.origins.component.PlayerOriginComponent.sync(PlayerOriginComponent.java:210) ~[Origins-1.18-1.3.1.jar:?]
at io.github.apace100.origins.content.OrbOfOriginItem.method_7836(OrbOfOriginItem.java:57) ~[Origins-1.18-1.3.1.jar:?]
at net.minecraft.class_1799.method_7913(class_1799.java:252) ~[server-intermediary.jar:?]
at net.minecraft.class_3225.method_14256(class_3225.java:282) ~[server-intermediary.jar:?]
at net.minecraft.class_3244.method_12065(class_3244.java:1093) ~[server-intermediary.jar:?]
at net.minecraft.class_2886.method_12550(class_2886.java:25) ~[server-intermediary.jar:?]
at net.minecraft.class_2886.method_11054(class_2886.java:7) ~[server-intermediary.jar:?]
at net.minecraft.class_2600.method_11072(class_2600.java:21) ~[server-intermediary.jar:?]
at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
at net.minecraft.class_1255.method_18859(class_1255.java:151) ~[server-intermediary.jar:?]
at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:780) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:162) ~[server-intermediary.jar:?]
at net.minecraft.class_1255.method_16075(class_1255.java:125) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:762) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:756) ~[server-intermediary.jar:?]
at net.minecraft.class_1255.method_18857(class_1255.java:134) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:741) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:688) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
at java.lang.Thread.run(Thread.java:833) [?:?]
```
I got no idea how it happened, but I had custom origins before and it started when i tried to modify one.
Even though i removed it from the datapacks, the error still occurs, and when i try to assign myself an origin with the command, i get the following message in console : `An unexpected error occurred trying to execute that command`, and then it randomly says `Failed to save player data for <my name>`.

The problem is that it works for other players on my server but for me i just can't change origin.

Thanks for the help.

**Comment by NoeMastrorillo** [comment]
Well I figured out it came after I wrongly used the command with `/origin set Me origins:origins ...` (with the s at origin).
