### ISSUE TITLE
Couldn't Place Player In World

### ISSUE THREAD

**Issue by IanuReeves** [apace100/origins-fabric#489]
This is 1.18 Minecraft. Origins Version: 1.18 1.3.0 I don't know if it's just me but I have a server with all the mods and data packs working. however, every time I load a single player world and have a data pack I want to add it either

1. It says it isn't stable and needs to be in safe mode
2. It says "Invalid Player Data" and cuts to the multiplayer menu
3. It says "Disconnected" and cuts to the multiplayer menu
 ##
I currently also have fabric API, mod menu, origins-classes, Pehkui, REI, and Architectury.

Here is the error: 

**Couldn't place player in world
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2960.toString()" because "$$0" is null
	at net.minecraft.class_2540.method_10812(class_2540.java:531)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at io.github.apace100.origins.origin.OriginLayer$ConditionedOrigin.write(OriginLayer.java:302)
	at io.github.apace100.origins.origin.OriginLayer.lambda$write$14(OriginLayer.java:195)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at io.github.apace100.origins.origin.OriginLayer.write(OriginLayer.java:195)
	at net.minecraft.class_3324.mdf1d2d0$lambda$openOriginsGui$1$3(class_3324.java:4477)
	at java.base/java.util.HashMap$Values.forEach(HashMap.java:1065)
	at net.minecraft.class_3324.handler$zoj000$openOriginsGui(class_3324.java:4476)
	at net.minecraft.class_3324.method_14570(class_3324.java:281)
	at net.minecraft.class_3248.method_33800(class_3248.java:130)
	at net.minecraft.class_3248.method_14384(class_3248.java:117)
	at net.minecraft.class_3248.redirect$zka000$handlePlayerJoin(class_3248.java:563)
	at net.minecraft.class_3248.method_18785(class_3248.java:67)
	at net.minecraft.class_2535.method_10754(class_2535.java:234)
	at net.minecraft.class_3242.method_14357(class_3242.java:183)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:890)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823)
	at net.minecraft.class_1132.method_3748(class_1132.java:99)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:833)**

**Comment by Fruitsnackl** [comment]
have you gotten the code to work yet? I have the same issue with the origins I'm developing and really need to figure it out

**Comment by IanuReeves** [comment]
Whoops, I accidentally closed the issue. I just reopened it, but basically I had an error with the code where I had something wrong with either the coding of the dimension, a problem with a power that had a keybind code issue, or the fact that I did a power that involved the change of the size of the player and did it wrong,  when I accidentally used an entity action as a power type, or sometimes changing the impact of an origin in my experience sometimes causes problems for strange reasons. although, I forgot how I fixed the error. I prove just scrapped the project or something so I'm sorry if this doesn't help you.

**Comment by DemonX3** [comment]
Can't believe I'm seeing this 4 years later completely unresolved.

**Comment by IanuReeves** [comment]
I'm unc now 😭
