### ISSUE TITLE
origins crashing when loading a world

### ISSUE THREAD

**Issue by ogkef** [apace100/origins-fabric#509]
i cant play minecraft with origins. when i try to load any world minecraft just crashes. i dont use optifine or anything like that.
1.16.5

---- Minecraft Crash Report ----
// You're mean.

Time: 20.03.22 01:01
Description: Rendering item

java.lang.NullPointerException: Rendering item
	at net.minecraft.class_2519.method_23256(class_2519.java:56)
	at net.minecraft.class_2487.method_10582(class_2487.java:182)
	at net.minecraft.class_2512.method_10684(class_2512.java:95)
	at net.minecraft.class_756.method_3166(class_756.java:79)
	at net.minecraft.class_918.method_23179(class_918.java:124)
	at net.minecraft.class_918.method_4021(class_918.java:300)
	at net.minecraft.class_918.method_4026(class_918.java:332)
	at net.minecraft.class_918.method_27953(class_918.java:318)
	at io.github.apace100.origins.screen.ChooseOriginScreen.renderOriginName(ChooseOriginScreen.java:205)
	at io.github.apace100.origins.screen.ChooseOriginScreen.renderOriginWindow(ChooseOriginScreen.java:175)
	at io.github.apace100.origins.screen.ChooseOriginScreen.method_25394(ChooseOriginScreen.java:165)
	at net.minecraft.class_757.method_3192(class_757.java:616)
	at net.minecraft.class_310.method_1523(class_310.java:1048)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_2519.method_23256(class_2519.java:56)
	at net.minecraft.class_2487.method_10582(class_2487.java:182)
	at net.minecraft.class_2512.method_10684(class_2512.java:95)
	at net.minecraft.class_756.method_3166(class_756.java:79)
	at net.minecraft.class_918.method_23179(class_918.java:124)
	at net.minecraft.class_918.method_4021(class_918.java:300)

-- Item being rendered --
Details:
	Item Type: player_head
	Item Damage: 0
	Item NBT: {}
	Item Foil: false
Stacktrace:
	at net.minecraft.class_918.method_4026(class_918.java:332)
	at net.minecraft.class_918.method_27953(class_918.java:318)
	at io.github.apace100.origins.screen.ChooseOriginScreen.renderOriginName(ChooseOriginScreen.java:205)
	at io.github.apace100.origins.screen.ChooseOriginScreen.renderOriginWindow(ChooseOriginScreen.java:175)
	at io.github.apace100.origins.screen.ChooseOriginScreen.method_25394(ChooseOriginScreen.java:165)

-- Screen render details --
Details:
	Screen name: io.github.apace100.origins.screen.ChooseOriginScreen
	Mouse location: Scaled: (200, 142). Absolute: (800.000000, 568.000000)
	Screen size: Scaled: (400, 285). Absolute: (1600, 1137). Scale factor of 4.000000

-- Affected level --
Details:
	All players: 1 total; [class_746['kefirzasty'/150, l='ClientLevel', x=-116.50, y=71.00, z=136.50]]
	Chunk stats: SodiumChunkCache: 441
	Level dimension: minecraft:overworld
	Level spawn location: World: (-112,72,128), Chunk: (at 0,4,0 in -7,8; contains blocks -112,0,128 to -97,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 115 game time, 115 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:699)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 8.1 (amd64) version 6.3
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 829742088 bytes (791 MB) / 1610612736 bytes (1536 MB) up to 6408896512 bytes (6112 MB)
	CPUs: 2
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx6105m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		boostedbrightness: Boosted Brightness 1.2.1
		cardinal-components-base: Cardinal Components API (base) 2.8.1
		cardinal-components-entity: Cardinal Components API (entities) 2.8.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.11.14
		extraorigins: Extra Origins 1.16.5-13
		fabric: Fabric API 0.30.0+1.16
		fabric-api-base: Fabric API Base 0.2.0+daa38b3d7d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.5+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.0.10+ca58154a7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.10+ca58154a7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.2+ca58154a7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.2+ca58154a7d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.1+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-models-v0: Fabric Models (v0) 0.2.1+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.3+ca58154a7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.1+ca58154a7d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.4+ca58154a7d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.1+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.13+ca58154a7d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.2+ca58154a7d
		fabric-rendering-v1: Fabric Rendering (v1) 1.5.1+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.0+c045166c7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.1+ca58154a7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-textures-v0: Fabric Textures (v0) 1.0.6+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabricloader: Fabric Loader 0.13.3
		fallflyinglib: FallFlyingLib 1.1.0
		genesis: Genesis 0.5.1
		java: Java HotSpot(TM) 64-Bit Server VM 8
		kanos_config: Kanos Config 0.1.4+1.14.4-1.17.1
		lithium: Lithium 0.6.6
		minecraft: Minecraft 1.16.5
		origins: Origins 0.7.3
		pehkui: Pehkui 3.1.0+1.14.4-1.18.1
		phosphor: Phosphor 0.6.0+build.7
		reach-entity-attributes: Reach Entity Attributes 1.1.1
		sodium: Sodium 0.1.0
		waila: Hwyla 1.9.22
		xaerominimap: Xaero's Minimap 21.2.0
	Launched Version: fabric-loader-0.13.3-1.16.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GT 730/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.35, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 2x Intel(R) Pentium(R) CPU G630 @ 2.70GHz

**Comment by itsdeadfrosty** [comment]
how nice of them to help u in a reasonable amount of time LOL
