### ISSUE TITLE
Using origins with Optifabric causes a crash!

### ISSUE THREAD

**Issue by TheAyes** [apace100/origins-fabric#538]
I'm unsure where this issue inherits from either Origins or Optifabric. I'll go and post the issue on their tracker if you can ensure it has nothing to do with the mod on your side!

```
[17:21:32] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.3
[17:21:32] [main/INFO]: Loading 58 mods:
	- additionalentityattributes 1.0.0+1.18.2 via apoli
	- apoli 2.3.3 via origins
	- calio 1.5.1 via apoli
	- cardinal-components-base 4.1.4 via apoli
	- cardinal-components-entity 4.1.4 via apoli
	- cloth-basic-math 0.6.0 via cloth-config
	- cloth-config 6.2.57 via apoli
	- fabric 0.51.1+1.18.2
	- fabric-api-base 0.4.4+d7c144a860 via fabric
	- fabric-api-lookup-api-v1 1.6.0+2373a54560 via fabric
	- fabric-biome-api-v1 8.0.4+7b0f312660 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-command-api-v1 1.1.9+d7c144a860 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.3+d82b939260 via fabric
	- fabric-convention-tags-v1 1.0.1+474e4f7960 via fabric
	- fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
	- fabric-dimensions-v1 2.1.17+2540745460 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.14+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.4.0+4457765560 via fabric
	- fabric-item-groups-v0 0.3.11+91896a4960 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-lifecycle-events-v1 2.0.3+2d83e92c60 via fabric
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.1.0+81ea5b3c60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.1.0+fe4ddef060 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.5.0+7faf0d8860 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 1.10.7+54e5b2ec60 via fabric
	- fabric-resource-conditions-api-v1 2.0.3+91b7aa6660 via fabric
	- fabric-resource-loader-v0 0.4.18+2de5574560 via fabric
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.2.0+1f6558e860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.6.0+2373a54560 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+bd8a4a1860 via fabric
	- fabricloader 0.14.3
	- java 18
	- minecraft 1.18.2
	- mm 2.3 via optifabric
	- optifabric 1.13.0
	- origins 1.4.1
	- playerabilitylib 1.5.0 via apoli
	- reach-entity-attributes 2.1.1 via origins
[17:21:32] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/Ayes/Desktop/MultiMC/libraries/net/fabricmc/sponge-mixin/0.11.3+mixin.0.8.5/sponge-mixin-0.11.3+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[17:21:32] [main/INFO]: Compatibility level set to JAVA_17
Found existing patched optifine jar, using that
[17:21:33] [main/WARN]: Configuration conflict: there is more than one oshi.properties file on the classpath
[17:21:33] [main/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[17:21:34] [main/ERROR]: Critical injection failure: LVT in net/minecraft/class_761::method_22710(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;)V has incompatible changes at opcode 1022 in callback apoli.mixins.json:WorldRendererMixin from mod apoli->@Inject::getEntity(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_3695;ZLnet/minecraft/class_243;DDDLnet/minecraft/class_1159;ZLnet/minecraft/class_4604;FZZLnet/minecraft/class_4597$class_4598;Ljava/util/Iterator;Lnet/minecraft/class_1297;)V.
 Expected: [Lnet/minecraft/class_3695;, Z, Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, F, Z, Z, Lnet/minecraft/class_4597$class_4598;, Ljava/util/Iterator;, Lnet/minecraft/class_1297;]
    Found: [Lnet/minecraft/class_3695;, Z, Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, Z, F, Z, Z, Z, Lnet/minecraft/class_4597$class_4598;]
Available: [Lnet/minecraft/class_3695;, Z, Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, Z, F, Z, Z, Z, Lnet/minecraft/class_4597$class_4598;, I, I, Ljava/util/Collection;, Ljava/util/Iterator;, Ljava/util/List;, Ljava/util/Iterator;, Lnet/minecraft/class_1297;, Lnet/minecraft/class_4597;, Lnet/minecraft/class_4618;, I]
[17:21:34] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.ExceptionInInitializerError
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:454) ~[fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.3.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.ExceptionInInitializerError
	at net.minecraft.class_128.method_568(class_128.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:343) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:151) ~[minecraft-1.18.2-client.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) ~[fabric-loader-0.14.3.jar:?]
	... 8 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_761 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:414) ~[fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:318) ~[fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:284) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:343) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:151) ~[minecraft-1.18.2-client.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) ~[fabric-loader-0.14.3.jar:?]
	... 8 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:409) ~[fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:318) ~[fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:284) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:343) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:151) ~[minecraft-1.18.2-client.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) ~[fabric-loader-0.14.3.jar:?]
	... 8 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_761::method_22710(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;)V has incompatible changes at opcode 1022 in callback apoli.mixins.json:WorldRendererMixin from mod apoli->@Inject::getEntity(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_3695;ZLnet/minecraft/class_243;DDDLnet/minecraft/class_1159;ZLnet/minecraft/class_4604;FZZLnet/minecraft/class_4597$class_4598;Ljava/util/Iterator;Lnet/minecraft/class_1297;)V.
 Expected: [Lnet/minecraft/class_3695;, Z, Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, F, Z, Z, Lnet/minecraft/class_4597$class_4598;, Ljava/util/Iterator;, Lnet/minecraft/class_1297;]
    Found: [Lnet/minecraft/class_3695;, Z, Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, Z, F, Z, Z, Z, Lnet/minecraft/class_4597$class_4598;]
Available: [Lnet/minecraft/class_3695;, Z, Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, Z, F, Z, Z, Z, Lnet/minecraft/class_4597$class_4598;, I, I, Ljava/util/Collection;, Ljava/util/Iterator;, Ljava/util/List;, Ljava/util/Iterator;, Lnet/minecraft/class_1297;, Lnet/minecraft/class_4597;, Lnet/minecraft/class_4618;, I]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:547) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.callback.CallbackInjector.inject(CallbackInjector.java:497) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.code.Injector.inject(Injector.java:276) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.inject(InjectionInfo.java:445) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1378) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.11.3+mixin.0.8.5.jar:0.11.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:409) ~[fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:318) ~[fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:284) ~[Optifine-mapped.jar:?]
	at net.minecraft.class_128.method_568(class_128.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_128.method_24305(class_128.java:343) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:151) ~[minecraft-1.18.2-client.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:577) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:452) ~[fabric-loader-0.14.3.jar:?]
	... 8 more
Process exited with code 1.
```

**Comment by apace100** [comment]
Origins and OptiFabric have only been compatible in the past because the OptiFabric team has put in additional effort into making their mod specifically compatible with Origins.
Since Origins is a mod that relies heavily on mixins, and OptiFabric (like Origins) touches quite a bit of the Minecraft code base, conflicts are bound to happen with every update I make.
I don't regard compatibility with OptiFabric as something I should strive for due to the aforementioned problem and the additional amount of work that would be required from my side in order to make this happen. There are enough alternatives to OptiFabric around which work just fine with Origins. If you're interested, [here's a list of those alternatives](https://lambdaurora.dev/optifine_alternatives/).
Otherwise, you'd need to wait for an update from the OptiFabric devs which restores compatibility, as it has been in the past whenever I updated Origins.

I apologize for any inconveniences this decision may be causing you.
