### ISSUE TITLE
Trinket compat: If you're an elytrian, and put on an elytra, it crashes the game

### ISSUE THREAD

**Issue by CammiePone** [apace100/origins-fabric#54]
I attempted to put an elytra on, because I forgot I was an elytrian, and I ended up getting this crash:
```---- Minecraft Crash Report ----
// You're mean.

Time: 12/6/20 1:26 AM
Description: mouseDragged event handler

java.lang.NullPointerException: mouseDragged event handler
	at io.github.apace100.origins.power.RestrictArmorPower.canEquip(RestrictArmorPower.java:19)
	at net.minecraft.class_1723$1.md6f8c54$lambda$preventArmorInsertion$0$0(class_1723.java:532)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.LinkedList$LLSpliterator.tryAdvance(LinkedList.java:1249)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at net.minecraft.class_1723$1.handler$dno000$preventArmorInsertion(class_1723.java:532)
	at net.minecraft.class_1723$1.method_7680(class_1723.java)
	at net.minecraft.class_481$class_484.method_7680(class_481.java:878)
	at net.minecraft.class_465.method_25403(class_465.java:433)
	at net.minecraft.class_481.method_25403(class_481.java:671)
	at net.minecraft.class_312.method_1602(class_312.java:194)
	at net.minecraft.class_437.method_25412(class_437.java:435)
	at net.minecraft.class_312.method_1600(class_312.java:194)
	at net.minecraft.class_312.method_22689(class_312.java:161)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22688(class_312.java:161)
	at org.lwjgl.glfw.GLFWCursorPosCallbackI.callback(GLFWCursorPosCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102)
	at net.minecraft.class_1041.method_15998(class_1041.java:308)
	at net.minecraft.class_310.method_1523(class_310.java:1068)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at io.github.apace100.origins.power.RestrictArmorPower.canEquip(RestrictArmorPower.java:19)
	at net.minecraft.class_1723$1.md6f8c54$lambda$preventArmorInsertion$0$0(class_1723.java:532)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.LinkedList$LLSpliterator.tryAdvance(LinkedList.java:1249)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at net.minecraft.class_1723$1.handler$dno000$preventArmorInsertion(class_1723.java:532)
	at net.minecraft.class_1723$1.method_7680(class_1723.java)
	at net.minecraft.class_481$class_484.method_7680(class_481.java:878)
	at net.minecraft.class_465.method_25403(class_465.java:433)
	at net.minecraft.class_481.method_25403(class_481.java:671)
	at net.minecraft.class_312.method_1602(class_312.java:194)

-- Affected screen --
Details:
	Screen name: net.minecraft.class_481
Stacktrace:
	at net.minecraft.class_437.method_25412(class_437.java:435)
	at net.minecraft.class_312.method_1600(class_312.java:194)
	at net.minecraft.class_312.method_22689(class_312.java:161)
	at net.minecraft.class_1255.execute(class_1255.java:94)
	at net.minecraft.class_312.method_22688(class_312.java:161)
	at org.lwjgl.glfw.GLFWCursorPosCallbackI.callback(GLFWCursorPosCallbackI.java:37)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:102)

-- Affected level --
Details:
	All players: 1 total; [class_746['Cammiebun'/104, l='ClientWorld minecraft:overworld', x=-175.24, y=74.00, z=-194.79]]
	Chunk stats: Client Chunks (ImmPtl) 1088
	Level dimension: minecraft:overworld
	Level spawn location: World: (-80,71,-144), Chunk: (at 0,4,0 in -5,-9; contains blocks -80,0,-144 to -65,255,-129), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 2070 game time, 2070 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:699)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1255071024 bytes (1196 MB) / 3900178432 bytes (3719 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 12
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8192m -Xms8192m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m
	Fabric Mods: 
		amecs: Amecs 1.3.2+mc.1.16.3
		amecsapi: Amecs API 1.1.1+mc1.16-rc1
		angerable-patch: Angerable Patch 1.1.0-1.16.4
		anthropophagy: Anthropophagy 1.16.4-3
		antighost: AntiGhost 1.16.4-fabric0.25.1-1.1.3
		anvil_fix: AnvilFix 1.1.3+build.7-1.16
		appleskin: AppleSkin 1.0.11
		artifacts: Artifacts 2.0.2+1.16.4-fabric
		artifice: Artifice 0.13.2+1.16.3
		artofalchemy: Art of Alchemy: Memoriam 1.0.0-rc4+1.16.4
		authme: Auth Me 1.4.0
		autoconfig1u: Auto Config v1 Updated 3.3.1
		battletowers: Battle Towers 3.2.1-beta-1.16.4
		bedspreads: Bedspreads 1.3.1-1.16.4
		better_mod_button: Better Mod Button 1.1.4
		bettercaves: YUNG's Better Caves 1.16.2-1.0.3
		betterdroppeditems: Better Dropped Items 1.2.4-1.16.2
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0
		betterslabs: Betterslabs 1.1.3
		betterthanmending: BetterThanMending 1.2.0
		betterweather: Better Weather 1.0.0
		blockus: Blockus 1.6.8+1.16.4
		blue_endless_jankson: jankson +
		bowinfinityfix: Bow Infinity Fix rv9
		bunch-o-trinkets: Bunch O' Trinkets 1.0.1
		cameraoverhaul: Camera Overhaul 1.0.1-fabric-1.16
		cardinal-components-base: Cardinal Components API (base) 2.7.9
		cardinal-components-entity: Cardinal Components API (entities) 2.7.9
		cardinal-components-item: Cardinal Components API (items) 2.7.9
		cardinal-components-util: Cardinal Components API (utilities) 2.7.5
		cardinal-components-world: Cardinal Components API (worlds) 2.5.0-nightly.1.16.2-rc2
		carpet: Carpet Mod in Fabric 1.4.20
		chat-up: Chat Up! 1.0
		cinderscapes: Cinderscapes 1.3.0+build.51
		cleancut: CleanCut mc1.16-2.1-fabric
		clear-skies: Clear Skies 1.5.48
		cleardespawn: Clear Despawn 1.16.4-fabric0.25.1-1.1.1
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.5
		cloth-config2: Cloth Config v4 4.8.3
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
		com_electronwill_night-config_core: core 3.6.0
		com_electronwill_night-config_toml: toml 3.6.0
		com_github_therandomlabs_trlutils-config: TRLUtils-Config master-SNAPSHOT
		com_github_therandomlabs_trlutils-fabric: TRLUtils-Fabric 1.16-SNAPSHOT
		com_squareup_moshi_moshi: moshi 1.9.2
		com_squareup_okio_okio: okio 1.16.0
		com_typesafe_config: config 1.4.0
		controlling: Controlling For Fabric 1.1.2
		cotton: Cotton 1.1.0
		cotton-cauldron: Cotton Cauldron 1.1.0
		cotton-client-commands: Cotton Client Commands 1.0.1+1.16-rc1
		cotton-commons: Cotton Commons 1.0.4
		cotton-config: Cotton Config 1.0.0-rc.7
		cotton-datapack: Cotton Datapack 1.0.7
		cotton-logging: Cotton Logging 1.0.0-rc.4
		cotton-player-events: Cotton Player Events 1.0.2
		couplings: Couplings 1.3.3
		crawl: Crawl 0.8.1
		crimsonmoon: Crimson Moon 1.2.3-1.16.2
		crowdin-translate: CrowdinTranslate 1.2
		customstars: Custom Stars 0.4.1
		customwindowtitle: Custom Window Title 1.1.0
		dark-loading-screen: Dark Loading Screen 1.5.0
		dataloader: Data Loader 2.1.0+mc1.16.1
		dehydration: Dehydration 1.0.8
		dynamicsoundfilters: Dynamic Sound Filters 1.1.3+1.16.2
		edit_sign: Edit Sign 2.1.3
		environmentz: EnvironmentZ 1.0.6
		extraorigins: Extra Origins 1.16.4-4
		fabric: Fabric API 0.27.1+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+6a2618f53a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+6a2618f53a
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+6a2618f53a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.0+e77439c73a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-diagonal-panes: Fabric Diagonal Panes 0.3.1
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.1+9a6c75813a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+6a2618f53a
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+6a2618f53a
		fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
		fabric-language-scala: Fabric Language Scala 0.3.2.12
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+6a2618f53a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
		fabric-models-v0: Fabric Models (v0) 0.1.1+6a2618f53a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b3a
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+6a2618f53a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: fabric-particles-v1 0.2.2+6a2618f53a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.1+285766753a
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+6a2618f53a
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db23a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
		fabric-rendering-v1: Fabric Rendering (v1) 1.4.0+6a2618f53a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.2+1944f3e03a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.1+f1d8af063a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.0+e77439c73a
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+a4467d2a3a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabrication: Fabrication 1.2.3_02
		fabricloader: Fabric Loader 0.10.8
		fallflyinglib: FallFlyingLib 1.1.0
		falling_tree: FallingTree 2.7.0
		fallingleaves: Falling Leaves 1.2
		fastbench: FastBench 2.3
		fastfurnace: FastFurnace 2.3
		fatxporbs: Fat Experience Orbs 0.0.9
		fiber: fiber 0.23.0-2
		fluidphysics: Fluid Physics 1.3.8+fabric-1.16.4
		gbfabrictools: GBfabrictools 1.3.1+1.16.4
		haema: Haema 1.3.1
		harmfulstonecutters: Harmful Stonecutters 1.0.1
		hookshot: Hookshot 10.0
		horseinfo: Horse Info 0.2.2-1.16.1
		hotfurnace: Hot Furnace 1.1.1
		iamverysmart: I Am Very Smart 2.1.0+mc1.16.1
		imm_ptl_core: Immersive Portals Core 0.49
		immersive_portals: Immersive Portals 0.49
		intotheomega: Into the Omega 1.1.2-beta-1.16.2
		inventorysorter: Inventory Sorter 1.7.4-1.16
		itemmodelfix: Item Model Fix 0.2.4
		jankson: Jankson 3.0.1+j1.2.0
		kayak: kayak 0.1.1.22
		kirin: Kirin UI 1.7-1.16.2
		kyrptconfig: Kytpt Config 1.1.2-1.16
		lakeside: Lakeside 1.0.3+1.16.4
		lambdabettergrass: LambdaBetterGrass 1.0.1+1.16.3
		lambdynlights: LambDynamicLights 1.3.2+1.16.4
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.2.2+1.16.3
		libstructure: LibStructure 1.5
		lightoverlay: Light Overlay 5.5.4
		linkart: Linkart unspecified
		lithium: Lithium 0.6.0
		lithium-api: Lithium API 0.6.0
		maelstrom_library: Maelstrom Library 0.4.1
		mambience: MAmbience 2.1.0+1.16.2
		minecraft: Minecraft 1.16.4
		mixedslab: Mixed Slab 1.16.3-1.2
		mm: Manningham Mills 2.1
		mob_proof_crystals: Mob proof crystals 1.0.0
		mobs_attempt_parkour: Mobs Attempt Parkour 0.2.1-1.16.3
		modmenu: Mod Menu 1.14.13+build.19
		modupdater: ModUpdater 1.1.11+1.16.2-rc2
		morepaths: More Paths 0.0.3
		mostructures: Mo' Structures 1.0.1+mc.1.16.4
		netherroof: NetherRoofMod 1.0.0
		nourish: Nourish 1.1.1
		numericping: NumericPing 1.0.2-fabric1.16.3
		okzoomer: Ok Zoomer 4.0.1+1.16.2
		onsoulfire: On Soul Fire 1.16.4-1
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
		origins: Origins 0.4.5
		origins-classes: Origins: Classes 1.1.0
		overworld_two: Overworld 2 1.0.3
		particlerain: Particle Rain 1.1.1
		patchouli: Patchouli 1.16-40-FABRIC
		pehkui: Pehkui 1.6.2+1.16.3
		phosphor: Phosphor 0.6.0+build.7
		piglessportals: Pigless Portals 1.0.0
		pling: Pling 1.2.0
		presencefootsteps: Presence Footsteps r28+1.16.2
		quiver: Quiver 2.16.1
		rare-ice: Rare Ice 0.2.2
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		realisticfirespread: Realistic Fire Spread 1.16.4-1
		repurposed_structures: Repurposed Structures 1.16.4-1.7.3
		respawnablepets: Respawnable Pets 1.16.4-1
		riptide_fix: Riptide Fix 1.2.0
		roughlyenoughitems: Roughly Enough Items 5.8.7
		roughlyenoughitems-api: REI (API) 5.8.7
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.7
		roughlyenoughitems-runtime: REI (Runtime) 5.8.7
		roughlyenoughresources: Roughly Enough Resources 2.1.2
		satin: Satin 1.4.1
		seasons: Fabric Seasons 1.0.3-BETA
		secretrooms: Secret Rooms 0.9.2+1.16.2
		shulkerboxtooltip: Shulker Box Tooltip 2.3.3+1.16.4
		silkspawners: SilkSpawners 1.0.0
		simpleplanes: simpleplanes 3.2.1
		spruceui: SpruceUI 1.6.4
		stairdoors-fabric: StairDoors Fabric 2.1.0
		statement: Statement 4.0.0+1.16.2
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stonecutter-tweaks: Stonecutter Tweaks 1.1.0-1.16
		structure-helpers: Structure Helpers 3.0.0
		telepistons: Telepistons 1.0.1
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.0+build.1
		terraform-config-api-v1: Terraform Config API (v1) 1.0.0+build.1
		terraform-dirt-api-v1: Terraform Dirt API (v1) 1.0.0+build.1
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.0+build.1
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.0+build.1
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.0+build.1
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.1+build.2
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.0+build.1
		terrestria: Terrestria 2.1.5+build.28
		trade: Trade 1.1.2
		trapexpansion: Trap Expansion 1.3.2
		traverse: Traverse 3.0.3+build.13
		tridentfixer: Repairable Tridents 1.0.0
		trinkets: Trinkets 2.6.7
		vanilladeathchest: VanillaDeathChest 1.16.3-1.11.0.7-fabric
		voyager: Voyager 1.0.0
		waila: Hwyla 1.9.22
		waystones: Waystones 1.0.10
		yungsapi: YUNG's API 1.16.4-Fabric-1
		zoob: Monster Of The Ocean Depths 2.5.0
	Patchouli open book context: n/a
	Launched Version: 1.16.4
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1660 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 457.51, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: fabric/fabric-renderer-api-v1, fabric/fabric-keybindings-v0, fabric/inventorysorter, fabric/step-height-entity-attribute, fabric/fabricloader, fabric/trinkets, fabric/artifice, fabric/fabric-containers-v0, fabric/fabric-object-builder-api-v1, fabric/fabric-game-rule-api-v1, fabric/fabric-api-base, fabric/artifacts, fabric/fabric-rendering-data-attachment-v1, fabric/fabric-textures-v0, fabric/fabric-rendering-fluids-v1, fabric/bedspreads, fabric/fabric-blockrenderlayer-v1, fabric/fabric-lifecycle-events-v1, fabric/fabric-renderer-registries-v1, fabric/fabric-loot-tables-v1, fabric/fabric, fabric/anvil_fix, fabric/artofalchemy, fabric/fabric-networking-v0, fabric/pling, fabric/fabric-networking-blockentity-v0, fabric/okzoomer, fabric/fabric-screen-handler-api-v1, fabric/modmenu, fabric/jankson, fabric/fabric-command-api-v1, fabric/amecsapi, fabric/betterdroppeditems, fabric/hookshot, fabric/fabric-tool-attribute-api-v1, fabric/fabric-renderer-indigo, fabric/battletowers, fabric/structure-helpers, fabric/anthropophagy, fabric/dark-loading-screen, fabric/fabric-events-interaction-v0, fabric/fabric-item-api-v1, fabric/fabric-crash-report-info-v1, fabric/libgui, fabric/statement, fabric/stairdoors-fabric, fabric/fabric-rendering-v0, fabric/fabric-rendering-v1, fabric/fabric-key-binding-api-v1, fabric/cloth-config2, fabric/nourish, fabric/better_mod_button, fabric/amecs, fabric/fabric-resource-loader-v0, fabric/autoconfig1u, fabric/antighost, fabric/fabric-content-registries-v0, fabric/fabric-tag-extensions-v0, fabric/fabric-biome-api-v1, fabric/staticdata, fabric/authme, fabric/fabric-registry-sync-v0, fabric/fabric-mining-levels-v0, fabric/fabric-events-lifecycle-v0, fabric/fabric-models-v0, fabric/fabric-item-groups-v0, fabric/bettermineshafts, fabric/fabric-object-builders-v0, fabric/betterslabs
	Current Language: English (US)
	CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz```

**Comment by apace100** [comment]
Hi, I couldn't reproduce this. Trying to put on an Elytra in the inventory doesn't work for me at all (it's prevented). Equipping an Elytra by right-clicking while holding it in your hand does work, but it does not produce a crash for me.

**Comment by CammiePone** [comment]
So just tested again, going through each mod one at a time. It appears to specifically be an issue with Trinkets when you try to drag it into the chestplate slot. It can be put in the cape slot, though. Not sure from which side this would need to be fixed though.
https://youtu.be/DaMdCTWyfqM

**Comment by apace100** [comment]
Thanks for testing so extensively! Changed title of the issue to reflect compatibility problem.
