### ISSUE TITLE
It crashed when I trie to open minecraft

### ISSUE THREAD

**Issue by unrusoanonimo** [apace100/origins-fabric#55]
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:208)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178)
	at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23)
	at net.fabricmc.loader.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:157)
	at net.fabricmc.loader.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:150)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.class_310.<init>(class_310.java:533)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_241, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 238356872 bytes (227 MB) / 773304320 bytes (737 MB) up to 7276331008 bytes (6939 MB)
	CPUs: 4
	JVM Flags: 5 total; -Xmn128M -Xmx6951M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -XX:+UseConcMarkSweepGC
	Fabric Mods: 
		adorn: Adorn 1.12.1+1.16.4
		advanced_runtime_resource_pack: Runtime Resource Pack 0.2.6
		allure: Allure 1.2.8
		appleskin: AppleSkin 1.0.11
		armorstandutils: Armor Stand Utils 1.0.1
		autoconfig1u: Auto Config v1 Updated 3.3.1
		automated_crafting: Automated Crafting 1.3.13+MC1.16.2-1.16.4
		bedspreads: Bedspreads 1.3.1-1.16.4
		better_wither_skeletons: Better Wither Skeletons 1.1.0
		bettercaves: YUNG's Better Caves 1.16.2-1.0.3
		betterend: Better End 0.7.1-beta
		bettergraves: Better Graves 0.4.1
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0
		biomemakeover: Biome Makeover 1.16.4-1.1.5
		blackstonetools: Blackstone Tools 1.2.0+1.16.1
		blockshifter: Blockshifter 1.3.2+fabric-1.16.4
		blockus: Blockus 1.6.8+1.16.4
		blue_endless_jankson: jankson 1.2.0
		cardinal-components-base: Cardinal Components API (base) 2.7.1
		cardinal-components-entity: Cardinal Components API (entities) 2.7.1
		carpet: Carpet Mod in Fabric 1.4.12
		carpet-extra: Carpet Extra 1.4.8
		carpet-tis-addition: Carpet TIS Addition 1.9.2
		cavebiomes: Cave Biomes 0.5.1
		chainmail: Chainmail 0.5.0
		cinderscapes: Cinderscapes 1.2.4+build.43-1.16.4
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.5
		cloth-config2: Cloth Config v4 4.8.3
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
		couplings: Couplings 1.3.3
		enderitemod: Enderite Mod 1.2.2
		expandedstorage: ExpandedStorage 5.6.31
		extraalchemy: Extra Alchemy 1.3.1
		extratnt: Extra TNT 1.0.1
		fabric: Fabric API 0.26.3+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.0+2e23b97c3a
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+6a2618f53a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+6a2618f53a
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+6a2618f53a
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+6a2618f53a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+6a2618f53a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+6a2618f53a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+6a2618f53a
		fabric-furnaces: Fabric Furnaces 1.3.2-1.16.2
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+6a2618f53a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+6a2618f53a
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+6a2618f53a
		fabric-language-kotlin: Fabric Language Kotlin 1.4.0+build.1
		fabric-language-scala: Fabric Language Scala 0.3.2.12
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+6a2618f53a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+6a2618f53a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+6a2618f53a
		fabric-models-v0: Fabric Models (v0) 0.1.1+6a2618f53a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b3a
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+6a2618f53a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+6a2618f53a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+6a2618f53a
		fabric-particles-v1: fabric-particles-v1 0.2.2+6a2618f53a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.1+285766753a
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+6a2618f53a
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+6a2618f53a
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db23a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+6a2618f53a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+6a2618f53a
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+6a2618f53a
		fabric-rendering-v1: Fabric Rendering (v1) 1.4.0+6a2618f53a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.2+1944f3e03a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+6a2618f53a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.1+f1d8af063a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+6a2618f53a
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+a4467d2a3a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+6a2618f53a
		fabric-tree-chopper: Fabric Tree Chopper 0.5.1
		fabricloader: Fabric Loader 0.10.8
		fallflyinglib: FallFlyingLib 1.1.0
		grindenchantments: Grind Enchantments 1.1.3+1.16.3
		horsestatsvanilla: Horse Stats Vanilla 4.1.4
		hplus: Hopper Plus 1.0.9
		inertia: Inertia Client 1.16.4
		infinitevillagertrading: InfiniteVillagerTrading 1.16.2-fabric0.17.2-1.1
		infinityfix: Infinity Fix 1.1.0
		jankson: Jankson 3.0.1+j1.2.0
		kyrptconfig: Kytpt Config 1.1.6-1.16
		libblockattributes_core: LibBlockAttributes (Core) 0.8.4
		libcd: LibCapableData 3.0.3+1.16.3
		libgui: LibGui 3.2.1+1.16.3
		libmultipart: LibMultiPart 0.4.3
		libmultipart_deps_container: LibMultiPart (Dependency Container) 0.4.3
		libnetworkstack: Lib Network Stack 0.4.1
		libstructure: LibStructure 1.5
		minecraft: Minecraft 1.16.4
		mm: Manningham Mills 2.0.1
		modmenu: Mod Menu 1.14.6+build.31
		morepaths: More Paths 0.0.3
		moretotems: More Totems 2.7.1
		netherite_plus: Netherite Plus Mod 1.1.0
		netheritehorsearmor: Netherite Horse Armor 0.4.3-1.16.3
		noexpensive: NoExpensive 1.16.4-Fabric-1.1.4
		onsoulfire: On Soul Fire 1.16.4-1
		org_jetbrains_annotations: annotations 20.0.0
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.4.0
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.4.0
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.9
		origins: Origins 0.4.5
		parchment: Parchment 1.0.2+1.15.2
		polymorph: Polymorph 0.0.5-1.16.3
		quickshulker: Quick Shulker 1.1.11-1.16
		reach-entity-attributes: Reach Entity Attribute 1.0.1
		roughlyenoughitems: Roughly Enough Items 5.8.7
		roughlyenoughitems-api: REI (API) 5.8.7
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.8.7
		roughlyenoughitems-runtime: REI (Runtime) 5.8.7
		roughlyenoughresources: Roughly Enough Resources 2.1.2
		sde: Stackable Damage Enchants 1.0.1
		sodium: Sodium 0.1.0
		stackablepotions: Stackable Potions 1.0.0
		static-content: Static Content 1.0.1-1.16.2
		staticdata: Static Data 1.1.2
		terraform-biome-builder-api-v1: Terraform Biome Builder API (v1) 1.0.0+build.1
		terraform-config-api-v1: Terraform Config API (v1) 1.0.0+build.1
		terraform-overworld-biome-extensions-api-v1: Terraform Overworld Biome Extensions API (v1) 1.0.0+build.1
		terraform-shapes-api-v1: Terraform Shapes API (v1) 1.0.0+build.1
		terraform-surfaces-api-v1: Terraform Surfaces API (v1) 1.0.0+build.1
		terraform-tree-api-v1: Terraform Tree API (v1) 1.0.0+build.1
		terraform-wood-api-v1: Terraform Wood API (v1) 1.0.0+build.1
		traverse: Traverse 3.0.3+build.13
		uncraftable: Uncraftables 1.3.4-1.16.1
		vanilla_parts: Vanilla Parts 1.1.4+1.16.3
		villagerhats: Villager Hats fabric-1.16.4-1.0.1
		waila: Hwyla 1.9.22
		wolveswitharmor: Wolves With Armor 1.5.2-1.16.2
		yungsapi: YUNG's API 1.16.4-Fabric-1
	Launched Version: fabric-loader-0.10.8-1.16.4
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 390.77, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 4x Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
#@!@# Game crashed! Crash report saved to: #@!@# C:\Users\joser\AppData\Roaming\.minecraft\crash-reports\crash-2020-12-08_12.38.46-client.txt
Here I am!
[VersionManager] Refreshing versions locally...
[VersionManager] Versions has been refreshed (57 ms)
[Launcher] Minecraft closed with exit code: -1
flush now
[Launcher] Launcher exited.
[Launcher] [Crash] Found crash report file: C:\Users\joser\AppData\Roaming\.minecraft\crash-reports\crash-2020-12-08_12.26.02-client.txt
[Crash] Found crash report file: C:\Users\joser\AppData\Roaming\.minecraft\crash-reports\crash-2020-12-08_12.26.02-client.txt
[Launcher] [Crash] Found crash report file: C:\Users\joser\AppData\Roaming\.minecraft\crash-reports\crash-2020-12-08_12.27.11-client.txt
[Crash] Found crash report file: C:\Users\joser\AppData\Roaming\.minecraft\crash-reports\crash-2020-12-08_12.27.11-client.txt
[Launcher] [Crash] Found crash report file: C:\Users\joser\AppData\Roaming\.minecraft\crash-reports\crash-2020-12-08_12.38.46-client.txt
[Crash] Found crash report file: C:\Users\joser\AppData\Roaming\.minecraft\crash-reports\crash-2020-12-08_12.38.46-client.txt
flush now

**Comment by apace100** [comment]
Sorry, but the log doesn't tell me anything helpful, and it doesn't even hint towards Origins. Are you sure this crash is Origins' fault? If so, please post the contents of the file located at "C:\Users\joser\AppData\Roaming\.minecraft\crash-reports\crash-2020-12-08_12.38.46-client.txt". That crash report probably has more information.

**Comment by unrusoanonimo** [comment]
[crash-2020-12-08_12.38.46-client.txt](https://github.com/apace100/origins-fabric/files/5679599/crash-2020-12-08_12.38.46-client.txt)
