### ISSUE TITLE
Dedicated server crash on startup (v1.4.1 for 1.18.2)

### ISSUE THREAD

**Issue by SomeHyena** [apace100/origins-fabric#561]
Whenever I try to start up a dedicated server to play with friends, I get an error. This is with no other mods but Fabric API (tried old versions as well) and Origins 1.4.1, or 1.4.0. -- I had other mods previously, but eventually narrowed it down to being an Origins problem, especially given the newest 1.19 patch notes mention dedicated server crash fixes on startup.

Uncaught exception in thread "main"
java.lang.RuntimeException: An exception occurred when launching the server!
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:71)
	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:25)
Caused by: java.lang.RuntimeException: Error creating Mixin config additionalentityattributes.mixins.json for mod additionalentityattributes
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:95)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:153)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
	... 1 more
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config additionalentityattributes.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:93)
	... 5 more
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.0 (ASM10_EXPERIMENTAL))
	at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1570)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 8 more

![c9f83101f95ad025ef8f79a8b1f4c20b](https://user-images.githubusercontent.com/65989142/174530841-68f93fb7-cb1d-490c-a74a-c8fe76828d82.png)

Issue seems to stem from compatibility level JAVA_17 being unable to be set, and playing with different jdk versions (both 17 and 18) cause this issue. My main jdk version used is 17.0.1.

Did not notice this problem until now as I was doing most of my testing for the mods in singleplayer, and v1.4.1 works perfectly fine in single player.

**Comment by SomeHyena** [comment]
And worth noting that this is an issue every time, even if the only 2 mods trying to launch on the server are Fabric API and Origins. It does not happen with only Fabric API. With Only Fabric API, it sets compatibility level to JAVA_16 by default.

**Comment by SomeHyena** [comment]
And it does this with Fabric loader versions 0.14.8 as well as 0.14.7

**Comment by SomeHyena** [comment]
It seems this is a byproduct of the launcher I use using an outdated Fabric installer; when manually downloading the fabric server launcher using installer version 0.11.0 from the Fabric website, this does not happen -- I had simply been installing a package for 1.18.2 + Fabric 1.14.8 / 1.14.7 using ATLauncher, and their Fabric Server Launcher *does* have this problem.

Could still pose an issue for people in a similar situation to mine, but the issue for me personally has been solved.
