### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by MertKExe** [apace100/origins-fabric#591]
**Must be ** this line:

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'origins'!

Fabric api, Fabric loader, Origins and other mods are latest version. It simply randomly appears on our server without any crash report. We cannot play without origins.

[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
[Pterodactyl Daemon]: Finished pulling Docker container image
container@pterodactyl~ java -version
openjdk version "17.0.2" 2022-01-18
OpenJDK Runtime Environment (build 17.0.2+8-86)
OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)
container@pterodactyl~ java -Xms128M -Xmx6144M -jar fabric-server-launch.jar
Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[18:38:38] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.9
[18:38:38] [main/INFO]: Loading 95 mods:
        - additionalentityattributes 1.0.0+1.19 via apoli
        - apoli 2.5.1 via origins
        - badpackets 0.1.2
        - calio 1.7.0 via apoli
        - cardinal-components-base 5.0.0-beta.1 via apoli
        - cardinal-components-entity 5.0.0-beta.1 via apoli
        - chime 1.3.0
        - chunky 1.2.217
        - cloth-api 4.0.65
        - cloth-basic-math 0.6.1 via cloth-api
        - cloth-client-events-v0 4.0.65 via cloth-api
        - cloth-common-events-v1 4.0.65 via cloth-api
        - cloth-config 7.0.74
        - cloth-utils-v1 4.0.65 via cloth-api
        - clumps 9.0.0+10
        - collective-fabric 4.27
        - com_electronwill_night-config_core 3.6.5 via forgeconfigapiport
        - com_electronwill_night-config_toml 3.6.5 via forgeconfigapiport
        - connectivity 1.19-3.2
        - fabric 0.57.0+1.19
        - fabric-api-base 0.4.9+e62f51a3a9 via fabric
        - fabric-api-lookup-api-v1 1.6.7+9ff28f40a9 via fabric
        - fabric-biome-api-v1 9.0.14+b2a4a624a9 via fabric
        - fabric-command-api-v1 1.2.6+f71b366fa9 via fabric
        - fabric-command-api-v2 2.1.2+0d55f585a9 via fabric
        - fabric-commands-v0 0.2.23+df3654b3a9 via fabric
        - fabric-containers-v0 0.1.27+df3654b3a9 via fabric
        - fabric-content-registries-v0 3.2.0+07df213ea9 via fabric
        - fabric-convention-tags-v1 1.0.8+37622d24a9 via fabric
        - fabric-crash-report-info-v1 0.2.3+bd0a0d4aa9 via fabric
        - fabric-data-generation-api-v1 5.1.1+a680b9b4a9 via fabric
        - fabric-dimensions-v1 2.1.28+a6d2f785a9 via fabric
        - fabric-entity-events-v1 1.4.16+9ff28f40a9 via fabric
        - fabric-events-interaction-v0 0.4.26+9ff28f40a9 via fabric
        - fabric-events-lifecycle-v0 0.2.25+df3654b3a9 via fabric
        - fabric-game-rule-api-v1 1.0.19+18990361a9 via fabric
        - fabric-item-api-v1 1.5.4+767db26ea9 via fabric
        - fabric-item-groups-v0 0.3.25+9ff28f40a9 via fabric
        - fabric-language-kotlin 1.8.2+kotlin.1.7.10
        - fabric-lifecycle-events-v1 2.1.0+33fbc738a9 via fabric
        - fabric-loot-api-v2 1.1.0+03a4e568a9 via fabric
        - fabric-loot-tables-v1 1.1.3+9e7660c6a9 via fabric
        - fabric-message-api-v1 1.0.1+513f4a59a9 via fabric
        - fabric-mining-level-api-v1 2.1.10+33fbc738a9 via fabric
        - fabric-networking-api-v1 1.0.27+7fe97409a9 via fabric
        - fabric-networking-v0 0.3.14+df3654b3a9 via fabric
        - fabric-object-builder-api-v1 4.0.7+9ff28f40a9 via fabric
        - fabric-particles-v1 1.0.8+dc39553aa9 via fabric
        - fabric-permissions-api-v0 0.1-SNAPSHOT via styledplayerlist
        - fabric-registry-sync-v0 0.9.17+23c4cfefa9 via fabric
        - fabric-rendering-data-attachment-v1 0.3.12+9ff28f40a9 via fabric
        - fabric-rendering-fluids-v1 3.0.5+9ff28f40a9 via fabric
        - fabric-resource-conditions-api-v1 2.0.9+e62f51a3a9 via fabric
        - fabric-resource-loader-v0 0.5.5+a6d2f785a9 via fabric
        - fabric-screen-handler-api-v1 1.2.6+9ff28f40a9 via fabric
        - fabric-transfer-api-v1 2.0.9+e62f51a3a9 via fabric
        - fabric-transitive-access-wideners-v1 1.1.1+9e7660c6a9 via fabric
        - fabricloader 0.14.9
        - fiber 0.23.0-2 via collective-fabric
        - flytre_lib 1.8.8
        - forgeconfigapiport 4.0.2
        - inventorysorter 1.8.10-1.19
        - java 17
        - justmobheads-fabric 5.4
        - justplayerheads-fabric 2.1
        - kyrptconfig 1.4.14-1.19 via inventorysorter
        - lazydfu 0.1.3
        - lithium 0.8.1
        - logprot 1.19.1-1.6
        - minecraft 1.19
        - org_jetbrains_kotlin_kotlin-reflect 1.7.10 via fabric-language-kotlin
        - org_jetbrains_kotlin_kotlin-stdlib 1.7.10 via fabric-language-kotlin
        - org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.10 via fabric-language-kotlin
        - org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.10 via fabric-language-kotlin
        - org_jetbrains_kotlinx_atomicfu-jvm 0.18.2 via fabric-language-kotlin
        - org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
        - org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
        - org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
        - org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.3 via fabric-language-kotlin
        - org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.3 via fabric-language-kotlin
        - org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.3 via fabric-language-kotlin
        - origins 1.6.2
        - pickupnotifier 4.0.0
        - placeholder-api 2.0.0-beta.3+1.19 via styledplayerlist
        - player-data-api 0.1.0+1.18 via styledplayerlist
        - playerabilitylib 1.6.0 via apoli
        - puzzleslib 4.0.18
        - reach-entity-attributes 2.3.0 via origins
        - sit 1.19-20
        - styledplayerlist 2.2.1+1.19
        - toofast 1.0.0
        - tooltiprareness 1.0.6
        - villagernames-fabric 3.6
        - welcomemessage-fabric 1.2
        - wthit 5.11.1
[18:38:38] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/container/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[18:38:38] [main/INFO]: Compatibility level set to JAVA_17
[18:38:38] [main/INFO]: Loaded configuration file for Lithium: 94 options available, 0 override(s) found
[18:38:43] [main/INFO]: Building unoptimized datafixer
[18:38:45] [main/INFO]: apoli.mixins.json:ItemSlotArgumentTypeAccessor from mod apoli->@Accessor[FIELD_GETTER]::getSlotNamesToSlotCommandId()Ljava/util/Map; should be static as its target is
[18:38:46] [main/INFO]: Apoli 2.5.1 has initialized. Ready to power up your game!
[18:38:46] [main/INFO]: [STDOUT]: Loading Collective (Fabric) version 4.27.
[18:38:46] [main/INFO]: Connectivity initialized
[18:38:46] [main/INFO]: Shields up!
[18:38:46] [main/INFO]: Origins 1.6.2 is initializing. Have fun!
[18:38:46] [main/INFO]: Constructing common components for mod pickupnotifier
[18:38:46] [main/INFO]: [WTHIT] Registering plugin waila:core at mcp.mobius.waila.plugin.core.WailaCore
[18:38:46] [main/INFO]: [WTHIT] Registering plugin waila:vanilla at mcp.mobius.waila.plugin.vanilla.WailaVanilla
[18:38:46] [main/INFO]: [WTHIT] Plugin config reloaded
[18:38:46] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'origins'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.9.jar:?]
        at net.minecraft.server.Main.main(Main.java:101) [server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-launch.jar:0.11.0]
Caused by: java.lang.NullPointerException: Cannot invoke "me.shedaniel.autoconfig.ConfigData.validatePostLoad()" because "this.config" is null
        at me.shedaniel.autoconfig.ConfigManager.load(ConfigManager.java:106) ~[cloth-config-7.0.74-fabric.jar:?]
        at me.shedaniel.autoconfig.ConfigManager.<init>(ConfigManager.java:53) ~[cloth-config-7.0.74-fabric.jar:?]
        at me.shedaniel.autoconfig.AutoConfig.register(AutoConfig.java:66) ~[cloth-config-7.0.74-fabric.jar:?]
        at io.github.apace100.origins.Origins.onInitialize(Origins.java:65) ~[Origins-1.19-1.6.2.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.9.jar:?]
        ... 8 more
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 0
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...

**Comment by eggohito** [comment]
Try deleting the `origins_server.json` file from your `.minecraft/config` folder

**Comment by MertKExe** [comment]
> Try deleting the `origins_server.json` file from your `.minecraft/config` folder

Yeah Fixed. It was empty.
