### ISSUE TITLE
Modify spawn to overworld biome causes freeze

### ISSUE THREAD

**Issue by Flyvee** [apace100/origins-fabric#616]
I've recently found in the most recent update, that with an origin's modify spawn set to an overworld biome that isn't currently rendered in causes the server to freeze and in single player to be unable to respawn without first relogging. The modify spawn into a specific biome in the end and in the nether still works fine with a little lag, but not with an unloaded in overworld biome. When I tested with a biome next to spawn or a biome another player is already in, it did work though.

**Comment by NideVice** [comment]
same problem

**Comment by Shivera057** [comment]
Having the same problem but it acts worse. Creating a new world spawns me in the right biome just fine, but dying makes the respawn button do nothing unless I had used a bed, even when I haven't moved from the initial spawn point, and relogging just puts me back on the same "You Died!" screen so I can't get back into the world. Trying the respawn button spits out this error in the log (btw this is origins 1.7.1 on Minecraft 1.19.2)

Failed to handle packet net.minecraft.class_2799@75682bee, suppressing error
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2338.method_10263()" because "pos" is null
	at net.minecraft.class_1937.method_8320(class_1937.java:7070)
	at net.minecraft.class_3222.handler$hcn000$onSetSpawnPoint(class_3222.java:20783)
	at net.minecraft.class_3222.method_26284(class_3222.java)
	at io.github.apace100.apoli.power.ModifyPlayerSpawnPower.onRemoved(ModifyPlayerSpawnPower.java:74)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.class_3324.handler$clf000$invokePowerRemovedCallback(class_3324.java:1085)
	at net.minecraft.class_3324.method_14556(class_3324.java)
	at net.minecraft.class_3244.method_12068(class_3244.java:1720)
	at net.minecraft.class_2799.method_12120(class_2799.java:24)
	at net.minecraft.class_2799.method_11054(class_2799.java:6)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
	at net.minecraft.class_1255.method_5383(class_1255.java:116)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)

I can recover the world by removing the modify spawn power from the origin's files and restarting my game, at least.
