### ISSUE TITLE
When hydrophobic origin class such as the enderman touches water, the game/server crashes, unplayable.

### ISSUE THREAD

**Issue by Vexicle** [apace100/origins-fabric#663]
I have been trying out origins mod with my friends, however they chose hydrophobic classes such as enderman and blaze, and each time they touch the water, the server crashes.

I have replicated this in a single-played world. Here's the logs:
`The game crashed whilst ticking entity
Error: java.lang.IllegalAccessError: class io.github.apace100.apoli.util.MiscUtil tried to access private method 'net.minecraft.class_1282 net.minecraft.class_8109.method_48795(net.minecraft.class_5321)' (io.github.apace100.apoli.util.MiscUtil and net.minecraft.class_8109 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @62e136d3)`

The server crash logs:
`net.minecraft.class_148: Ticking entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:905) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:828) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:675) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:266) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalAccessError: class io.github.apace100.apoli.util.MiscUtil tried to access private method 'net.minecraft.class_1282 net.minecraft.class_8109.method_48795(net.minecraft.class_5321)' (io.github.apace100.apoli.util.MiscUtil and net.minecraft.class_8109 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @1ed4004b)
	at io.github.apace100.apoli.util.MiscUtil.createDamageSource(MiscUtil.java:63) ~[apoli-2.8.0-6ecfaa0a07ac1d54.jar:?]
	at io.github.apace100.apoli.power.DamageOverTimePower.getDamageSource(DamageOverTimePower.java:86) ~[apoli-2.8.0-6ecfaa0a07ac1d54.jar:?]
	at io.github.apace100.apoli.power.DamageOverTimePower.doDamage(DamageOverTimePower.java:77) ~[apoli-2.8.0-6ecfaa0a07ac1d54.jar:?]
	at io.github.apace100.apoli.power.DamageOverTimePower.tick(DamageOverTimePower.java:67) ~[apoli-2.8.0-6ecfaa0a07ac1d54.jar:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
	at io.github.apace100.apoli.component.PowerHolderComponentImpl.serverTick(PowerHolderComponentImpl.java:172) ~[apoli-2.8.0-6ecfaa0a07ac1d54.jar:?]
	at dev.onyxstudios.cca._generated_.GeneratedComponentContainer_EntityImpl_class_1657_13562080.tickServerComponents(Unknown Source) ~[?:?]
	at net.minecraft.class_3218.handler$zhb000$cardinal-components-entity$tick(class_3218.java:3212) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18762(class_3218.java:722) ~[server-intermediary.jar:?]
	at net.minecraft.class_1937.method_18472(class_1937.java:488) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_31420(class_3218.java:371) ~[server-intermediary.jar:?]
	at net.minecraft.class_5574.method_31791(class_5574.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:339) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901) ~[server-intermediary.jar:?]
	... 5 more`
Hope to get this fixed soon!

**Comment by apace100** [comment]
Hey, sorry for that!
You need to update Fabric API to a newer version.

I forgot to add this dependency check to the mod metadata, which is why the
game doesn't warn you about it when you start it.

Sorry for the inconvenience.
