### ISSUE TITLE
Could not get layer from id 'origins:origin', as it doesn't exist!

### ISSUE THREAD

**Issue by ellldee** [apace100/origins-fabric#696]
I tried to join my friend's server, it worked until I picked my origin and decided to crash. I tried again and again, tweaking things, looking through things to make sure that everything is correct, I've found nothing and it's still not working.

Here's the crash report:

---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2023-09-26 20:46:04
Description: Rendering screen

java.lang.IllegalArgumentException: Could not get layer from id 'origins:origin', as it doesn't exist!
	at io.github.apace100.origins.origin.OriginLayers.getLayer(OriginLayers.java:78)
	at io.github.apace100.origins.power.OriginsEntityConditions.lambda$register$1(OriginsEntityConditions.java:30)
	at io.github.apace100.apoli.power.factory.condition.ConditionFactory$Instance.isFulfilled(ConditionFactory.java:44)
	at io.github.apace100.apoli.power.factory.condition.ConditionFactory$Instance.test(ConditionFactory.java:35)
	at io.github.apace100.apoli.power.factory.condition.EntityConditions.lambda$register$1(EntityConditions.java:69)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.LinkedList$LLSpliterator.tryAdvance(LinkedList.java:1256)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637)
	at io.github.apace100.apoli.power.factory.condition.EntityConditions.lambda$register$2(EntityConditions.java:68)
	at io.github.apace100.apoli.power.factory.condition.ConditionFactory$Instance.isFulfilled(ConditionFactory.java:44)
	at io.github.apace100.apoli.power.factory.condition.ConditionFactory$Instance.test(ConditionFactory.java:35)
	at io.github.apace100.origins.origin.OriginLayer$ConditionedOrigin.isConditionFulfilled(OriginLayer.java:342)
	at io.github.apace100.origins.origin.OriginLayer.lambda$getOrigins$1(OriginLayer.java:119)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.github.apace100.origins.origin.OriginLayer.getOrigins(OriginLayer.java:119)
	at io.github.apace100.origins.origin.OriginLayer.getOriginOptionCount(OriginLayer.java:123)
	at io.github.apace100.origins.screen.WaitForNextLayerScreen.<init>(WaitForNextLayerScreen.java:28)
	at io.github.apace100.origins.screen.ChooseOriginScreen.openNextLayerScreen(ChooseOriginScreen.java:72)
	at io.github.apace100.origins.screen.ChooseOriginScreen.method_25394(ChooseOriginScreen.java:147)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at io.github.apace100.origins.origin.OriginLayers.getLayer(OriginLayers.java:78)
	at io.github.apace100.origins.power.OriginsEntityConditions.lambda$register$1(OriginsEntityConditions.java:30)
	at io.github.apace100.apoli.power.factory.condition.ConditionFactory$Instance.isFulfilled(ConditionFactory.java:44)
	at io.github.apace100.apoli.power.factory.condition.ConditionFactory$Instance.test(ConditionFactory.java:35)
	at io.github.apace100.apoli.power.factory.condition.EntityConditions.lambda$register$1(EntityConditions.java:69)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.LinkedList$LLSpliterator.tryAdvance(LinkedList.java:1256)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:637)
	at io.github.apace100.apoli.power.factory.condition.EntityConditions.lambda$register$2(EntityConditions.java:68)
	at io.github.apace100.apoli.power.factory.condition.ConditionFactory$Instance.isFulfilled(ConditionFactory.java:44)
	at io.github.apace100.apoli.power.factory.condition.ConditionFactory$Instance.test(ConditionFactory.java:35)
	at io.github.apace100.origins.origin.OriginLayer$ConditionedOrigin.isConditionFulfilled(OriginLayer.java:342)
	at io.github.apace100.origins.origin.OriginLayer.lambda$getOrigins$1(OriginLayer.java:119)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.github.apace100.origins.origin.OriginLayer.getOrigins(OriginLayer.java:119)
	at io.github.apace100.origins.origin.OriginLayer.getOriginOptionCount(OriginLayer.java:123)
	at io.github.apace100.origins.screen.WaitForNextLayerScreen.<init>(WaitForNextLayerScreen.java:28)
	at io.github.apace100.origins.screen.ChooseOriginScreen.openNextLayerScreen(ChooseOriginScreen.java:72)
	at io.github.apace100.origins.screen.ChooseOriginScreen.method_25394(ChooseOriginScreen.java:147)
	at net.minecraft.class_437.method_47413(class_437.java:110)

Any ideas on what's going on?

Thanks.

**Comment by BrainDifff** [comment]
mine doesnt crash but i get the same error

**Comment by ellldee** [comment]
I fixed it by deleting my player data in the server.
