### ISSUE TITLE
When i use the Orb of Origin, game is cracked and also i can`t play that world.

### ISSUE THREAD

**Issue by freeant72** [apace100/origins-fabric#736]
The loading window where the world is spawned will be 100%, but then there will be a crack and you will be kicked out of the game.
I use 1.20.1

**Comment by freeant72** [comment]
---- Minecraft Crash Report ----
// 'CRASH CORD IS HERE'

Time: 2024-03-12 14:59:49
Description: Rendering item

java.lang.ClassCastException: class com.mojang.authlib.minecraft.MinecraftProfileTexture$Type cannot be cast to class net.minecraft.class_2484$class_2485 (com.mojang.authlib.minecraft.MinecraftProfileTexture$Type and net.minecraft.class_2484$class_2485 are in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @36f0f1be)
	at net.minecraft.class_836.wrapOperation$mjf000$variantsandventures$getIdentifier(class_836.java:2052)
	at net.minecraft.class_836.method_3578(class_836.java:114)
	at net.minecraft.class_756.method_3166(class_756.java:112)
	at net.minecraft.class_918.redirect$fdd000$geckolib$cancelRender(class_918.java:6535)
	at net.minecraft.class_918.method_23179(class_918.java:126)
	at net.minecraft.class_332.method_51425(class_332.java:531)
	at net.minecraft.class_332.method_51424(class_332.java:511)
	at net.minecraft.class_332.method_51427(class_332.java:491)
	at io.github.apace100.origins.screen.ChooseOriginScreen.renderOriginChoicesBox(ChooseOriginScreen.java:645)
	at io.github.apace100.origins.screen.ChooseOriginScreen.handler$zcm000$altorigingui$addRendering(ChooseOriginScreen.java:619)
	at io.github.apace100.origins.screen.ChooseOriginScreen.method_25394(ChooseOriginScreen.java:151)
	at net.minecraft.class_437.method_47413(class_437.java:110)
	at net.minecraft.class_757.mixinextras$bridge$method_47413$305(class_757.java)
	at net.minecraft.class_757.wrapOperation$gek000$konkrete$wrapRenderScreenKonkrete(class_757.java:9635)
	at net.minecraft.class_757.method_3192(class_757.java:945)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by forkiesassds** [comment]
This should not happen at all. Either you're using a modified version to use 3rd party skin/auth servers, which is usually only used by players who play pirated copies of the game or something is SERIOUSLY wrong.

Edit: Seems like you're using a version of the mod for the wrong Minecraft version. But looking from the logs it could also be GeckoLib

**Comment by freeant72** [comment]
> This should not happen at all. Either you're using a modified version to use 3rd party skin/auth servers, which is usually only used by players who play pirated copies of the game or something is SERIOUSLY wrong.
> 
> Edit: Seems like you're using a version of the mod for the wrong Minecraft version. But looking from the logs it could also be GeckoLib

Oh. I see.

I bought and use Minecraft with my official Microsoft ID

I think it's probably a crash in the mod, and I've decided that GeckoLib or another loader isn't the latest version (to use this mod).

Thank you for your reply. I hope you will continue to have good modes. = ]

**Comment by forkiesassds** [comment]
> Thank you for your reply. I hope you will continue to have good modes. = ]

FYI: I am not the creator of this mod.
