### ISSUE TITLE
Error executing task on Server net.minecraft.class_148: Loading entity NBT

### ISSUE THREAD

**Issue by Lunaticol** [apace100/origins-fabric#763]
Issue occurs whenever origins have powers add/changed/removed. It seems to only happen to specific origins and not all. You have the manually reset the origin data on the player to fix it.

```[17:44:56] [Server thread/ERROR]: Error while reading power holder data: Could not get power type from id 'apocalypse:geneticist/craft_stabilizer', as it was not registered!
[17:44:56] [Server thread/INFO]: [STDOUT]: Negative index in crash report handler (0/20)
[17:44:56] [Server thread/ERROR]: Error executing task on Server
net.minecraft.class_148: Loading entity NBT
	at net.minecraft.class_1297.method_5651(class_1297.java:1939) ~[server-intermediary.jar:?]
	at net.minecraft.class_29.method_261(class_29.java:54) ~[server-intermediary.jar:?]
	at net.minecraft.class_3324.method_14600(class_3324.java:378) ~[server-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:164) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.method_33800(class_3248.java:131) ~[server-intermediary.jar:?]
	at net.minecraft.class_3248.mdb8c936$frozenlib$lambda$applySyncHandler$0$1(class_3248.java:2054) ~[server-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[server-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:782) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:164) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:764) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:758) ~[server-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:742) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.handler$bfi000$carpet$modifiedRunLoop(MinecraftServer.java:18951) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.NullPointerException```

**Comment by Lunaticol** [comment]
1.20.1 1.10.0 btw
