### ISSUE TITLE
merling REALY needs water 

### ISSUE THREAD

**Issue by Xlemonlime** [apace100/origins-fabric#772]
when ever you take dmg as merling the world crashes and it sends u to the server menu saying you disconnected and the menu turns black and white that's what happened to me at least very annoying

![2024-08-25_13 09 44](https://github.com/user-attachments/assets/18b2dd7f-340b-4b16-b0d8-47481e4b67b9)

(i had to make a github accout just for this)

**Comment by Xlemonlime** [comment]
added note this only  happens when you take (dry?) damage

**Comment by eggohito** [comment]
Which version of Origins are you using?

**Comment by Xlemonlime** [comment]
the latest version

**Comment by Xlemonlime** [comment]
nvm it stoped happening for some reason

**Comment by MaizIsLost** [comment]
This is also happening to me and a few friends on a modded server. Merling takes damage due air and everyone in the vicinity crashes. Sometimes it works and other times it breaks as well. No clue what's causing it because the bug disappears occasionally.

**Comment by eggohito** [comment]
Can you send your output logs? There isn't really much to work on since there is little to no information about this issue, and the output logs should help provide at least a hint on what exactly is going on 🤔

**Comment by MaizIsLost** [comment]
Just loaded up a new instance and had the issue occur to make sure it wasn't a modded capatibility issue. I believe this is the log you're looking for? If not I might need a little more help I haven't really done bug reporting before sadly.

12:50:33.606
net.minecraft.class_163
Render thread
Loaded 2 advancements
12:50:36.329
net.minecraft.class_2545
Netty Server IO #1
Error sending packet clientbound/minecraft:damage_event
io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:damage_event'
	at net.minecraft.class_9136.method_56426(class_9136.java:55)
	at net.minecraft.class_9136.encode(class_9136.java:14)
	at net.minecraft.class_2545.method_10838(class_2545.java:26)
	at net.minecraft.class_2545.encode(class_2545.java:12)
	at io.netty.handler.codec.MessageToByteEncoder.write(MessageToByteEncoder.java:107)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:113)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
	at io.netty.channel.ChannelOutboundHandlerAdapter.write(ChannelOutboundHandlerAdapter.java:113)
	at net.minecraft.class_2535$2.write(class_2535.java:530)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:881)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851)
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010)
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296)
	at net.minecraft.class_2535.method_36942(class_2535.java:350)
	at net.minecraft.class_2535.method_52917(class_2535.java:345)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.IllegalArgumentException: Can't find id for 'Reference{ResourceKey[minecraft:damage_type / origins:no_water_for_gills]=class_8110[msgId=no_water_for_gills, scaling=NEVER, exhaustion=0.1, effects=HURT, deathMessageType=DEFAULT]}' in map net.minecraft.class_2378$1@21ff25ad
	at net.minecraft.class_2359.method_56158(class_2359.java:27)
	at net.minecraft.class_9135$16.method_56423(class_9135.java:484)
	at net.minecraft.class_9135$16.encode(class_9135.java:471)
	at net.minecraft.class_8143.method_55873(class_8143.java:57)
	at net.minecraft.class_9139$6.encode(class_9139.java:42)
	at net.minecraft.class_9139$9.method_56442(class_9139.java:97)
	at net.minecraft.class_9139$9.encode(class_9139.java:87)
	at net.minecraft.class_9136.method_56426(class_9136.java:53)
	... 31 more
12:50:36.412
net.minecraft.class_3244
Server thread
MaizIsLost lost connection: Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:damage_event'
12:50:36.413
net.minecraft.server.MinecraftServer
Server thread
MaizIsLost left the game
12:50:36.441
net.minecraft.class_8609
Server thread
Stopping singleplayer server as player logged out
12:50:36.465
net.minecraft.server.MinecraftServer
Server thread
Stopping server
12:50:36.467
net.minecraft.server.MinecraftServer
Server thread
Saving players
12:50:36.467
net.minecraft.server.MinecraftServer
Server thread
Saving worlds
12:50:36.680
net.minecraft.server.MinecraftServer
Server thread
Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
12:50:37.298
net.minecraft.server.MinecraftServer
Server thread
Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
12:50:37.313
net.minecraft.server.MinecraftServer
Server thread
Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
12:50:37.343
net.minecraft.server.MinecraftServer
Server thread
ThreadedAnvilChunkStorage (New World): All chunks are saved
12:50:37.343
net.minecraft.server.MinecraftServer
Server thread
ThreadedAnvilChunkStorage (DIM1): All chunks are saved
12:50:37.343
net.minecraft.server.MinecraftServer
Server thread
ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
12:50:37.343
net.minecraft.server.MinecraftServer
Server thread
ThreadedAnvilChunkStorage: All dimensions are saved
12:50:37.537
net.minecraft.class_8673
Render thread
Client disconnected with reason: Internal Exception: io.netty.handler.codec.EncoderException: Failed to encode packet 'clientbound/minecraft:damage_event'

**Comment by eggohito** [comment]
This should now be fixed in the recent alpha versions
