### ISSUE TITLE
[1.21.1][Bug] Possible conflict with the mod "Eldritch Mobs" causes mobs to not spawn/load in and dissapear.

### ISSUE THREAD

**Issue by KorvasSol** [apace100/origins-fabric#781]
**Every Mod used**
- Fabric API 0.105.0
- Origins 1.13.0 Alpha 9
- Eldritch Mobs 1.16.1
- Cloth Config 15.0.140(Dependancy for Eldritch Mobs)

**Description:**

Whenever Eldritch Mobs and Origins is enabled on a server/world together they cause mobs to not spawn, existing mobs to vanish, and spams the log with the following.

<html>
<body>

[Server thread/WARN]: Failed to create mob
--
11380 | java.lang.NullPointerException: null

</body>
</html>

**Server log when you try to summon a mob through console:**

summon villager 100 100 100
[21:39:08] [Server thread/WARN]: Exception loading entity: 
java.lang.NullPointerException: null
at org.ladysnake.cca.api.v3.component.ComponentKey.maybeGet(ComponentKey.java:117) ~[cardinal-components-base-6.1.0-5fe249cd0025a395.jar:?]
at io.github.apace100.apoli.component.PowerHolderComponent.hasPowerType(PowerHolderComponent.java:288) ~[apoli-2.12.0-alpha.12+mc.1.21.x-9ff829e735a4c292.jar:?]
at io.github.apace100.apoli.power.type.ModifyTypeTagPowerType.doesApply(ModifyTypeTagPowerType.java:57) ~[apoli-2.12.0-alpha.12+mc.1.21.x-9ff829e735a4c292.jar:?]
at net.minecraft.class_1299.modifyReturnValue$zbk000$apoli$inTagProxy(class_1299.java:782) ~[server-intermediary.jar:?]
at net.minecraft.class_1299.method_20210(class_1299.java:675) ~[server-intermediary.jar:?]
at net.hyper_pigeon.eldritch_mobs.component.MobModifierComponent.canBeBuffed(MobModifierComponent.java:55) ~[eldritch-mobs-1.16.1.jar:?]
at net.hyper_pigeon.eldritch_mobs.component.MobModifierComponent.<init>(MobModifierComponent.java:48) ~[eldritch-mobs-1.16.1.jar:?]
at org.ladysnake.cca.internal.entity.CardinalEntityInternals.createEntityComponentContainer(CardinalEntityInternals.java:62) ~[cardinal-components-entity-6.1.0-f47ebfaf99d32b59.jar:?]
at net.minecraft.class_1297.handler$zed000$cardinal-components-entity$initDataTracker(class_1297.java:5054) ~[server-intermediary.jar:?]
at net.minecraft.class_1297.<init>(class_1297.java:315) ~[server-intermediary.jar:?]
at net.minecraft.class_1309.<init>(class_1309.java:270) ~[server-intermediary.jar:?]
at net.minecraft.class_1308.<init>(class_1308.java:148) ~[server-intermediary.jar:?]
at net.minecraft.class_1314.<init>(class_1314.java:17) ~[server-intermediary.jar:?]
at net.minecraft.class_1296.<init>(class_1296.java:29) ~[server-intermediary.jar:?]
at net.minecraft.class_3988.<init>(class_3988.java:58) ~[server-intermediary.jar:?]
at net.minecraft.class_1646.<init>(class_1646.java:201) ~[server-intermediary.jar:?]
at net.minecraft.class_1646.<init>(class_1646.java:197) ~[server-intermediary.jar:?]
at net.minecraft.class_1299.method_5883(class_1299.java:552) ~[server-intermediary.jar:?]
at net.minecraft.class_1299.method_17846(class_1299.java:556) ~[server-intermediary.jar:?]
at java.base/java.util.Optional.map(Optional.java:260) ~[?:?]
at net.minecraft.class_1299.method_5892(class_1299.java:556) ~[server-intermediary.jar:?]
at net.minecraft.class_1299.method_17848(class_1299.java:644) ~[server-intermediary.jar:?]
at net.minecraft.class_1299.method_17842(class_1299.java:595) ~[server-intermediary.jar:?]
at net.minecraft.class_3138.method_48758(class_3138.java:67) ~[server-intermediary.jar:?]
at net.minecraft.class_3138.method_13694(class_3138.java:86) ~[server-intermediary.jar:?]
at net.minecraft.class_3138.method_13689(class_3138.java:47) ~[server-intermediary.jar:?]
at com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:73) ~[brigadier-1.3.10.jar:?]
at net.minecraft.class_8865.method_54416(class_8865.java:29) ~[server-intermediary.jar:?]
at net.minecraft.class_8865.execute(class_8865.java:13) ~[server-intermediary.jar:?]
at net.minecraft.class_8856.method_54405(class_8856.java:8) ~[server-intermediary.jar:?]
at net.minecraft.class_8847.method_54388(class_8847.java:8) ~[server-intermediary.jar:?]
at net.minecraft.class_8854.method_54390(class_8854.java:107) ~[server-intermediary.jar:?]
at net.minecraft.class_2170.method_54313(class_2170.java:379) ~[server-intermediary.jar:?]
at net.minecraft.class_2170.method_9249(class_2170.java:309) ~[server-intermediary.jar:?]
at net.minecraft.class_2170.method_44252(class_2170.java:299) ~[server-intermediary.jar:?]
at net.minecraft.class_3176.method_13941(class_3176.java:318) ~[server-intermediary.jar:?]
at net.minecraft.class_3176.method_3813(class_3176.java:300) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:912) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697) ~[server-intermediary.jar:?]
at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:281) ~[server-intermediary.jar:?]
at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[21:39:08] [Server thread/INFO]: Unable to summon entity

**Comment by eggohito** [comment]
This is very strange. 🤔 Does this happen consistently? Also seems to happen with other mods too (like with Thermoo, as reported in https://github.com/apace100/apoli/issues/251)
